// ofxManifold — authoring grid and node-movement conformance vector runner.
//
// Reads tests/vectors/grids.vec, generated by tests/ref/reference_grids.py.
// The reference snaps by brute force over a wide window; the C++ rounds and
// checks a small neighbourhood. Agreement is what shows the shortcut is safe.

#include "../src/authoring/ofxManifoldGrid.h"
#include "../src/core/ofxManifold2D.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + name + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

void expectKeyword(std::istringstream& in, const char* kw) {
    std::string tok; in >> tok;
    if (tok != kw) {
        std::cerr << "malformed vector: expected " << kw << ", saw " << tok
                  << "\n";
        std::exit(2);
    }
}

// FREE | LATTICE ux uy vx vy ox oy angle | POLAR cx cy dr spokes angle
Grid readGrid(std::istringstream& in) {
    std::string kind; in >> kind;
    if (kind == "FREE") return Grid::free();
    if (kind == "LATTICE") {
        float ux, uy, vx, vy, ox, oy, a;
        in >> ux >> uy >> vx >> vy >> ox >> oy >> a;
        return Grid::lattice({ux, uy}, {vx, vy}, {ox, oy}, a);
    }
    if (kind == "POLAR") {
        float cx, cy, dr, a; int sp;
        in >> cx >> cy >> dr >> sp >> a;
        return Grid::polar({cx, cy}, dr, sp, a);
    }
    std::cerr << "unknown grid kind: " << kind << "\n";
    std::exit(2);
}

// "ADDR i j" | "ADDR NONE" | "ADDR ANY"
// Returns 0 for a concrete address, 1 for NONE, 2 for ANY.
int readAddr(std::istringstream& in, GridAddress& a) {
    std::string t; in >> t;
    if (t == "NONE") return 1;
    if (t == "ANY") return 2;
    a.a = std::stoi(t);
    in >> a.b;
    a.valid = true;
    return 0;
}

std::string show(const GridAddress& a) {
    if (!a.valid) return "none";
    return "(" + std::to_string(a.a) + ", " + std::to_string(a.b) + ")";
}

// "k:x,y" tokens until a keyword
std::map<NodeID, glm::vec2> readPoints(std::istringstream& in) {
    std::map<NodeID, glm::vec2> m;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        const std::size_t c = tok.find(':');
        if (c == std::string::npos) { in.clear(); in.seekg(mark); break; }
        const std::size_t k = tok.find(',', c);
        m[static_cast<NodeID>(std::stoul(tok.substr(0, c)))] = {
            std::stof(tok.substr(c + 1, k - c - 1)),
            std::stof(tok.substr(k + 1))};
    }
    return m;
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/grids.vec";
    std::ifstream f(path);
    if (!f) { std::cerr << "cannot open: " << path << "\n"; return 2; }

    std::cout << "ofxManifold grids\nvectors: " << path << "\n\n";

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind; in >> kind;
        if (kind == "TOL") { in >> tolerance; continue; }

        std::string name, cls; in >> name >> cls;
        std::ostringstream d;

        if (kind == "SNAP") {
            const Grid g = readGrid(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "EXPECT");
            float ex, ey; in >> ex >> ey;
            expectKeyword(in, "ADDR");
            GridAddress want;
            const int wk = readAddr(in, want);

            const SnapResult r = g.snap({px, py});
            bool ok = close(r.point.x, ex) && close(r.point.y, ey);
            if (!ok) {
                d << "expected (" << std::fixed << std::setprecision(6)
                  << ex << ", " << ey << "), got (" << r.point.x << ", "
                  << r.point.y << ")";
            }
            if (ok && wk == 0 && r.address != want) {
                ok = false;
                d << "right point, wrong address: expected " << show(want)
                  << ", got " << show(r.address);
            }
            if (ok && wk == 1 && r.address.valid) {
                ok = false;
                d << "free mode returned an address " << show(r.address);
            }
            record(cls, name, ok, d.str());

        } else if (kind == "ADDRRT") {
            const Grid g = readGrid(in);
            expectKeyword(in, "ADDR");
            GridAddress a;
            readAddr(in, a);
            const SnapResult r = g.snap(g.point(a));
            const bool ok = (r.address == a);
            if (!ok) d << show(a) << " -> position -> " << show(r.address);
            record(cls, name, ok, d.str());

        } else if (kind == "NESTS") {
            // Every point of the coarse grid is a point of the fine one.
            const Grid coarse = readGrid(in);
            expectKeyword(in, "INTO");
            const Grid fine = readGrid(in);
            bool ok = true;
            for (int i = -4; i <= 4 && ok; ++i) {
                for (int j = -4; j <= 4 && ok; ++j) {
                    const glm::vec2 p = coarse.point({i, j, true});
                    const SnapResult r = fine.snap(p);
                    if (!close(r.point.x, p.x) || !close(r.point.y, p.y)) {
                        ok = false;
                        d << "coarse point (" << i << ", " << j
                          << ") is not a point of the finer grid";
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "HYST") {
            const Grid g = readGrid(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "CURRENT");
            GridAddress cur;
            readAddr(in, cur);
            expectKeyword(in, "DEAD");
            float dead; in >> dead;
            expectKeyword(in, "ADDR");
            GridAddress want;
            readAddr(in, want);

            const SnapResult r = g.snapHysteresis({px, py}, cur, dead);
            const bool ok = (r.address == want);
            if (!ok) d << "expected " << show(want) << ", got "
                       << show(r.address);
            record(cls, name, ok, d.str());

        } else if (kind == "BATCH") {
            expectKeyword(in, "NODES");
            const auto nodes = readPoints(in);
            expectKeyword(in, "REGIONS");
            std::vector<std::vector<NodeID>> regions;
            std::string tok;
            while (in >> tok && tok != "MOVES") {
                std::vector<NodeID> r;
                std::stringstream ss(tok);
                std::string id;
                while (std::getline(ss, id, ',')) {
                    r.push_back(static_cast<NodeID>(std::stoul(id)));
                }
                regions.push_back(r);
            }
            const auto moves = readPoints(in);
            expectKeyword(in, "ACCEPT");
            int want; in >> want;

            Manifold2D m;
            for (const auto& n : nodes) {
                m.addNode("n" + std::to_string(n.first), n.second);
            }
            for (const auto& r : regions) m.addRegion(r);

            std::vector<std::pair<NodeID, glm::vec2>> mv(moves.begin(),
                                                         moves.end());
            const bool got = m.setNodePositions(mv);
            bool ok = (got ? 1 : 0) == want;
            if (!ok) d << (want ? "expected the batch to be accepted"
                                : "expected the batch to be refused");

            // All or nothing: after a refusal EVERY node is where it was;
            // after acceptance every moved node is where it was sent.
            for (const auto& n : nodes) {
                if (!ok) break;
                const auto it = moves.find(n.first);
                const glm::vec2 expect = (got && it != moves.end())
                                       ? it->second : n.second;
                const glm::vec2 have = m.node(n.first).position;
                if (!close(have.x, expect.x) || !close(have.y, expect.y)) {
                    ok = false;
                    d << "node " << n.first << " is at (" << have.x << ", "
                      << have.y << "), expected (" << expect.x << ", "
                      << expect.y << ")"
                      << (got ? "" : " -- a refused batch must change nothing");
                }
            }

            // A single move must reach the same verdict through the
            // single-node path. They share one implementation; this is the
            // check that they keep sharing it.
            if (ok && moves.size() == 1) {
                Manifold2D m1;
                for (const auto& n : nodes) {
                    m1.addNode("n" + std::to_string(n.first), n.second);
                }
                for (const auto& r : regions) m1.addRegion(r);
                const bool single = m1.setNodePosition(moves.begin()->first,
                                                       moves.begin()->second);
                if (single != got) {
                    ok = false;
                    d << "setNodePosition() and setNodePositions() disagree";
                }
            }
            record(cls, name, ok, d.str());

        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass; fail += t.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
