// ofxManifold — Manifold2D conformance vector runner.
//
// Reads tests/vectors/manifold.vec, generated by the independent Python
// reference in tests/ref/reference_manifold.py. The reference determines
// containment with the edge-sign test; the C++ under test uses barycentric
// non-negativity. Same predicate, unrelated arithmetic.
//
// Class meanings are as in the triangle suite:
//   ANALYTIC  known by hand from the constructed topology
//   CROSS     from the Python reference
//   SPEC      a rule we invented; green means self-consistent, not correct

#include "../src/core/ofxManifoldEvaluator.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };

std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;
std::string currentManifold;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + currentManifold + " / " + name
                           + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls
              << std::setw(20) << currentManifold << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

// A manifold under test, with the name bookkeeping the vector file uses.
struct Fixture {
    Manifold2D manifold;
    std::vector<std::string> regionNames;

    RegionID regionByName(const std::string& n) const {
        for (std::size_t i = 0; i < regionNames.size(); ++i) {
            if (regionNames[i] == n) return static_cast<RegionID>(i);
        }
        return InvalidRegion;
    }
    const std::string& regionName(RegionID r) const {
        static const std::string none = "NONE";
        return (r < regionNames.size()) ? regionNames[r] : none;
    }
};

void runQuery(Fixture& fx, std::istringstream& in) {
    std::string name, cls, expectRegion;
    float px, py;
    in >> name >> cls >> px >> py >> expectRegion;

    // Remaining tokens are node=weight pairs.
    std::vector<std::pair<std::string, float>> expect;
    std::string tok;
    while (in >> tok) {
        const std::size_t eq = tok.find('=');
        if (eq == std::string::npos) continue;
        expect.emplace_back(tok.substr(0, eq),
                            std::stof(tok.substr(eq + 1)));
    }

    const Evaluation e = fx.manifold.evaluate({px, py});

    if (expectRegion == "NONE") {
        if (!e.inside && e.weights.empty()
            && e.regionID == InvalidRegion) {
            record(cls, name, true, "");
            return;
        }
        std::ostringstream d;
        d << "expected outside the hull, got region "
          << fx.regionName(e.regionID) << " with " << e.weights.size()
          << " weights";
        record(cls, name, false, d.str());
        return;
    }

    if (!e.inside) {
        record(cls, name, false,
               "expected region " + expectRegion + ", got outside");
        return;
    }

    const std::string got = fx.regionName(e.regionID);
    if (got != expectRegion) {
        record(cls, name, false,
               "expected region " + expectRegion + ", got " + got);
        return;
    }

    // Identity must be retained: the result is checked by NODE NAME, not by
    // position in the array. An implementation that returned correct weights
    // attached to the wrong nodes would pass a positional check.
    std::ostringstream d;
    bool ok = e.weights.size() == expect.size();
    if (!ok) {
        d << "expected " << expect.size() << " weighted nodes, got "
          << e.weights.size();
    } else {
        float sum = 0.0f;
        for (const auto& want : expect) {
            const NodeID id = fx.manifold.findNode(want.first);
            bool found = false;
            for (const auto& wn : e.weights) {
                if (wn.id != id) continue;
                found = true;
                sum += wn.weight;
                if (!close(wn.weight, want.second)) {
                    ok = false;
                    d << "\n      node " << want.first << ": expected "
                      << std::fixed << std::setprecision(9) << want.second
                      << ", got " << wn.weight;
                }
                break;
            }
            if (!found) {
                ok = false;
                d << "\n      node " << want.first << " missing from result";
            }
        }
        // Partition of unity, asserted regardless of the expected values.
        if (ok && std::fabs(sum - 1.0f) > tolerance) {
            ok = false;
            d << "\n      weights sum to " << std::fixed
              << std::setprecision(12) << sum << ", not 1";
        }
    }
    record(cls, name, ok, d.str());
}

void runTopology(Fixture& fx, std::istringstream& in) {
    std::string cls;
    int wantTJ, wantOrphan, wantDup;
    in >> cls >> wantTJ >> wantOrphan >> wantDup;

    const TopologyReport rep = fx.manifold.validate();
    const int gotTJ     = static_cast<int>(rep.tJunctions.size());
    const int gotOrphan = static_cast<int>(rep.orphans.size());
    const int gotDup    = static_cast<int>(rep.duplicates.size());

    const bool ok = gotTJ == wantTJ && gotOrphan == wantOrphan
                 && gotDup == wantDup;

    if (ok) {
        // clean() must agree with the counts. A report that listed faults but
        // still called itself clean would be worse than one that missed them.
        const bool expectClean = (wantTJ + wantOrphan + wantDup) == 0;
        if (rep.clean() != expectClean) {
            record(cls, "topology", false,
                   "counts correct but clean() disagrees with them");
            return;
        }
        record(cls, "topology", true, "");
        return;
    }

    std::ostringstream d;
    d << "expected  T-junctions " << wantTJ << ", orphans " << wantOrphan
      << ", duplicates " << wantDup
      << "\n      got       T-junctions " << gotTJ << ", orphans "
      << gotOrphan << ", duplicates " << gotDup;
    for (const auto& t : rep.tJunctions) {
        d << "\n      T-junction: node " << fx.manifold.node(t.node).name
          << " on edge " << fx.manifold.node(t.edgeA).name << "-"
          << fx.manifold.node(t.edgeB).name
          << " of region " << fx.regionName(t.region);
    }
    for (NodeID n : rep.orphans) {
        d << "\n      orphan: " << fx.manifold.node(n).name;
    }
    record(cls, "topology", false, d.str());
}

// Forward, then inverse, back to the same point. Neither direction serves as
// the authority for the other, which is what makes this worth having.
void runRoundTrip(Fixture& fx, std::istringstream& in) {
    std::string name, cls, tok;
    float px, py;
    in >> name >> cls >> px >> py >> tok;

    const Evaluation e = fx.manifold.evaluate({px, py});

    if (tok == "NONE") {
        record(cls, name, !e.inside, "expected outside the hull");
        return;
    }
    float ex = std::stof(tok), ey; int wantWellPosed;
    in >> ey >> wantWellPosed;

    if (!e.inside) {
        record(cls, name, false, "forward evaluation reported outside");
        return;
    }

    const Manifold2D::InversePosition ip = fx.manifold.positionOf(e.weights);

    std::ostringstream d;
    bool ok = true;
    if (!close(ip.position.x, ex) || !close(ip.position.y, ey)) {
        ok = false;
        d << "expected position (" << std::fixed << std::setprecision(9)
          << ex << ", " << ey << ")\n      got      (" << ip.position.x
          << ", " << ip.position.y << ")";
    }
    // The round trip must also return to the point it started from. Agreeing
    // with the reference while both drift from the input would pass the check
    // above and mean nothing.
    if (!close(ip.position.x, px) || !close(ip.position.y, py)) {
        ok = false;
        d << "\n      did not return to the input point (" << px << ", "
          << py << ")";
    }
    if (ip.wellPosed != (wantWellPosed != 0)) {
        ok = false;
        d << "\n      wellPosed expected " << (wantWellPosed != 0)
          << ", got " << ip.wellPosed;
    }
    record(cls, name, ok, d.str());
}

void runInverse(Fixture& fx, std::istringstream& in) {
    std::string name, cls, tok;
    float ex, ey; int wantWellPosed;
    in >> name >> cls >> ex >> ey >> wantWellPosed;

    std::vector<WeightedNode> w;
    while (in >> tok) {
        const std::size_t eq = tok.find('=');
        if (eq == std::string::npos) continue;
        w.push_back(WeightedNode{fx.manifold.findNode(tok.substr(0, eq)),
                                 std::stof(tok.substr(eq + 1))});
    }

    const Manifold2D::InversePosition ip = fx.manifold.positionOf(w);

    std::ostringstream d;
    bool ok = true;
    if (!close(ip.position.x, ex) || !close(ip.position.y, ey)) {
        ok = false;
        d << "expected (" << std::fixed << std::setprecision(9) << ex << ", "
          << ey << ")\n      got      (" << ip.position.x << ", "
          << ip.position.y << ")";
    }
    if (ip.wellPosed != (wantWellPosed != 0)) {
        ok = false;
        d << "\n      wellPosed expected " << (wantWellPosed != 0)
          << ", got " << ip.wellPosed;
    }
    record(cls, name, ok, d.str());
}

// setNodePosition, restored afterwards so record order does not matter.
void runMove(Fixture& fx, std::istringstream& in) {
    std::string name, cls, nodeName;
    float nx, ny; int wantAccept;
    in >> name >> cls >> nodeName >> nx >> ny >> wantAccept;

    const NodeID id = fx.manifold.findNode(nodeName);
    if (id == InvalidNode) {
        record(cls, name, false, "no such node: " + nodeName);
        return;
    }
    const glm::vec2 before = fx.manifold.node(id).position;
    const bool accepted = fx.manifold.setNodePosition(id, {nx, ny});

    std::ostringstream d;
    bool ok = accepted == (wantAccept != 0);
    if (!ok) {
        d << (wantAccept ? "expected the move to be accepted, it was refused"
                         : "expected the move to be refused, it was accepted");
    } else if (accepted) {
        // An accepted move must actually have moved the node.
        const glm::vec2 now = fx.manifold.node(id).position;
        if (!close(now.x, nx) || !close(now.y, ny)) {
            ok = false;
            d << "accepted, but the node did not move";
        }
    } else {
        // A refused move must leave the node exactly where it was.
        const glm::vec2 now = fx.manifold.node(id).position;
        if (!close(now.x, before.x) || !close(now.y, before.y)) {
            ok = false;
            d << "refused, but the node moved anyway";
        }
    }
    fx.manifold.setNodePosition(id, before);
    record(cls, name, ok, d.str());
}

// A source walked through a sequence of points on ONE Evaluator. This is what
// distinguishes the hint from a plain scan: in an overlap the answer depends
// on where the source came from, and that is the intended behaviour.
void runTrack(Fixture& fx, std::istringstream& in) {
    std::string name, cls;
    in >> name >> cls;

    Evaluator ev(fx.manifold);
    std::ostringstream d;
    bool ok = true;
    int step = 0;

    float px, py;
    std::string want;
    while (in >> px >> py >> want) {
        const Evaluation e = ev.evaluate({px, py});
        const std::string got = e.inside ? fx.regionName(e.regionID) : "NONE";
        if (got != want) {
            ok = false;
            d << "\n      step " << step << " at (" << px << ", " << py
              << "): expected " << want << ", got " << got;
        }
        // Leaving the hull must clear the hint. A stale hint would make
        // re-entry depend on where the source left, which no author asked for.
        if (!e.inside && ev.hint() != InvalidRegion) {
            ok = false;
            d << "\n      step " << step << ": outside the hull but the hint"
                 " was not cleared";
        }
        ++step;
    }
    record(cls, name, ok, d.str());
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/manifold.vec";

    std::ifstream f(path);
    if (!f) {
        std::cerr << "cannot open vector file: " << path << "\n";
        return 2;
    }

    std::cout << "ofxManifold Manifold2D\n"
              << "vectors: " << path << "\n\n";

    Fixture fx;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind;
        in >> kind;

        if (kind == "TOL") {
            in >> tolerance;
        } else if (kind == "MANIFOLD") {
            fx = Fixture{};
            in >> currentManifold;
        } else if (kind == "NODE") {
            std::string name; float x, y, w;
            in >> name >> x >> y >> w;
            fx.manifold.addNode(name, {x, y}, w);
        } else if (kind == "TRI") {
            std::string rname, a, b, c;
            in >> rname >> a >> b >> c;
            const RegionID r = fx.manifold.addTriangle(
                fx.manifold.findNode(a),
                fx.manifold.findNode(b),
                fx.manifold.findNode(c));
            if (r == InvalidRegion) {
                std::cerr << "manifold " << currentManifold
                          << ": addTriangle refused " << rname << "\n";
                return 2;
            }
            fx.regionNames.push_back(rname);
        } else if (kind == "QUERY") {
            runQuery(fx, in);
        } else if (kind == "ROUNDTRIP") {
            runRoundTrip(fx, in);
        } else if (kind == "INVERSE") {
            runInverse(fx, in);
        } else if (kind == "MOVE") {
            runMove(fx, in);
        } else if (kind == "TRACK") {
            runTrack(fx, in);
        } else if (kind == "TOPOLOGY") {
            runTopology(fx, in);
        } else if (kind == "END") {
            // fixture stays until the next MANIFOLD
        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass;
        fail += t.fail;
    }

    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }

    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
