// ofxManifold — generalized region conformance vector runner.
//
// Reads tests/vectors/regions.vec, generated by tests/ref/reference_regions.py.
// Regions here are built through Manifold2D::addRegion, so what is tested is
// the kernel as a consumer reaches it, not solveRing() in isolation.

#include "../src/core/ofxManifold2D.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + name + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

void expectKeyword(std::istringstream& in, const char* kw) {
    std::string tok; in >> tok;
    if (tok != kw) {
        std::cerr << "malformed vector: expected " << kw << ", saw " << tok
                  << "\n";
        std::exit(2);
    }
}

// "x,y x,y ..." until the next keyword.
std::vector<glm::vec2> readPoly(std::istringstream& in) {
    std::vector<glm::vec2> p;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        const std::size_t c = tok.find(',');
        if (c == std::string::npos) { in.clear(); in.seekg(mark); break; }
        p.emplace_back(std::stof(tok.substr(0, c)),
                       std::stof(tok.substr(c + 1)));
    }
    return p;
}

// Build a manifold holding exactly one region over these positions.
bool build(const std::vector<glm::vec2>& poly, Manifold2D& m,
           RegionID& r) {
    m = Manifold2D();
    std::vector<NodeID> ids;
    for (std::size_t i = 0; i < poly.size(); ++i) {
        ids.push_back(m.addNode("n" + std::to_string(i), poly[i]));
    }
    r = m.addRegion(ids);
    return r != InvalidRegion;
}

// Weights in ring order, zero for any node not in the result.
std::vector<float> ringWeights(const Manifold2D& m, const Evaluation& e) {
    std::vector<float> w(m.nodeCount(), 0.0f);
    for (const auto& wn : e.weights) w[wn.id] = wn.weight;
    return w;
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/regions.vec";
    std::ifstream f(path);
    if (!f) { std::cerr << "cannot open: " << path << "\n"; return 2; }

    std::cout << "ofxManifold regions\nvectors: " << path << "\n\n";

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind; in >> kind;
        if (kind == "TOL") { in >> tolerance; continue; }

        std::string name, cls; in >> name >> cls;
        std::ostringstream d;

        if (kind == "N3AGREE") {
            // The triangle path and the MVC path must agree at N = 3. This is
            // what makes MVC an extension rather than a replacement: without
            // it, adding a fourth node to a region would change what the
            // first three meant.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;

            const BarycentricResult b =
                solveRaw(poly[0], poly[1], poly[2], {px, py});
            const RingResult r = solveRing(poly, {px, py});

            bool ok = b.valid && r.valid && r.w.size() == 3;
            if (ok) {
                for (int i = 0; i < 3; ++i) {
                    if (!close(b.w[i], r.w[i])) {
                        ok = false;
                        d << "\n      node " << i << ": triangle "
                          << std::fixed << std::setprecision(9) << b.w[i]
                          << ", MVC " << r.w[i];
                    }
                }
            } else {
                d << "one of the two solves reported invalid";
            }
            record(cls, name, ok, d.str());

        } else if (kind == "EVAL") {
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "EXPECT");
            std::vector<float> want; float x;
            while (in >> x) want.push_back(x);

            Manifold2D m; RegionID r;
            if (!build(poly, m, r)) {
                record(cls, name, false,
                       "region refused: " + m.lastRegionError());
                continue;
            }
            // Evaluate the region directly rather than through containment,
            // because a point ON a vertex or edge is exactly what several of
            // these vectors test and containment has its own tolerance.
            std::vector<float> bias(poly.size(), 1.0f);
            const RingResult rr = m.region(r).evaluate(poly, {px, py}, bias);

            bool ok = rr.valid && rr.w.size() == want.size();
            if (!ok) {
                d << "expected " << want.size() << " weights, got "
                  << rr.w.size() << (rr.valid ? "" : " (invalid)");
            } else {
                for (std::size_t i = 0; i < want.size(); ++i) {
                    if (!close(rr.w[i], want[i])) {
                        ok = false;
                        d << "\n      node " << i << ": expected "
                          << std::fixed << std::setprecision(9) << want[i]
                          << ", got " << rr.w[i];
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "CONTAINS") {
            // Through Manifold2D::evaluate(), the path a consumer takes. The
            // solver can be right while containment throws its answer away.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "INSIDE");   int wantIn;  in >> wantIn;
            expectKeyword(in, "NEGATIVE");
            std::string negTok; in >> negTok;
            // ANY: the boundary vectors assert containment only. On an edge
            // the far vertices carry last-digit noise either side of zero.
            const bool negAny = (negTok == "ANY");
            const int wantNeg = negAny ? 0 : std::stoi(negTok);
            expectKeyword(in, "EXPECT");
            std::vector<float> want; float x;
            while (in >> x) want.push_back(x);

            Manifold2D m; RegionID r;
            if (!build(poly, m, r)) {
                record(cls, name, false, "region refused"); continue;
            }
            const Evaluation e = m.evaluate({px, py});
            bool ok = (e.inside ? 1 : 0) == wantIn;
            if (!ok) {
                d << (wantIn ? "point is geometrically INSIDE the region and "
                               "evaluate() reported it outside"
                             : "point is outside the region and evaluate() "
                               "reported it inside");
            }
            if (ok && wantIn) {
                bool neg = false;
                for (const auto& wn : e.weights) if (wn.weight < -1e-6f) neg = true;
                if (!negAny && (neg ? 1 : 0) != wantNeg) {
                    ok = false;
                    d << "expected a negative weight to reach the consumer";
                }
                const std::vector<float> got = ringWeights(m, e);
                for (std::size_t i = 0; ok && i < want.size(); ++i) {
                    if (!close(got[i], want[i])) {
                        ok = false;
                        d << "\n      node " << i << ": expected "
                          << std::fixed << std::setprecision(9) << want[i]
                          << ", got " << got[i];
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "EVALBIAS") {
            // Bias on a polygon region, which every existing bias vector
            // missed because they are all on triangles.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "BIAS");
            std::vector<float> bias; std::string tok;
            while (in >> tok && tok != "EXPECT") bias.push_back(std::stof(tok));
            std::vector<float> want; float x;
            while (in >> x) want.push_back(x);

            Manifold2D m;
            std::vector<NodeID> ids;
            for (std::size_t i = 0; i < poly.size(); ++i) {
                ids.push_back(m.addNode("n" + std::to_string(i), poly[i],
                                        bias[i]));
            }
            if (m.addRegion(ids) == InvalidRegion) {
                record(cls, name, false, "region refused"); continue;
            }
            // Through Manifold2D::evaluate, so the bias is read from the
            // nodes exactly as a consumer's would be.
            const Evaluation e = m.evaluate({px, py});
            const std::vector<float> got = ringWeights(m, e);
            bool ok = e.inside && got.size() == want.size();
            if (ok) {
                for (std::size_t i = 0; i < want.size(); ++i) {
                    if (!close(got[i], want[i])) {
                        ok = false;
                        d << "\n      node " << i << ": expected "
                          << std::fixed << std::setprecision(9) << want[i]
                          << ", got " << got[i];
                    }
                }
            } else {
                d << "point reported outside, or wrong arity";
            }
            record(cls, name, ok, d.str());

        } else if (kind == "VARIES") {
            // Non-invariance, asserted. MVC under a non-uniform scale or a
            // shear MUST move the weights; if it did not, whatever produced
            // them would not be computing mean-value coordinates.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            expectKeyword(in, "FROM");
            std::vector<float> from; std::string tok;
            while (in >> tok && tok != "BYATLEAST") from.push_back(std::stof(tok));
            float atLeast; in >> atLeast;

            const RingResult r = solveRing(poly, {px, py});
            float worst = 0.0f;
            for (std::size_t i = 0; i < r.w.size() && i < from.size(); ++i) {
                worst = std::max(worst, std::fabs(r.w[i] - from[i]));
            }
            const bool ok = r.valid && worst >= atLeast;
            if (!ok) d << "weights moved by only " << worst
                       << "; MVC is not affine invariant, so a non-uniform "
                          "map must move them by at least " << atLeast;
            record(cls, name, ok, d.str());

        } else if (kind == "SUMONE") {
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "AT");
            float px, py; in >> px >> py;
            Manifold2D m; RegionID r;
            if (!build(poly, m, r)) {
                record(cls, name, false, "region refused"); continue;
            }
            std::vector<float> bias(poly.size(), 1.0f);
            const RingResult rr = m.region(r).evaluate(poly, {px, py}, bias);
            float s = 0.0f;
            for (float w : rr.w) s += w;
            const bool ok = rr.valid && close(s, 1.0f);
            if (!ok) d << "weights sum to " << std::fixed
                       << std::setprecision(9) << s;
            record(cls, name, ok, d.str());

        } else if (kind == "CONTINUOUS") {
            // The edge special case is a separate formula. It has to JOIN the
            // general one, or there is a visible seam every time a point runs
            // along an edge.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "ON");
            float ox, oy; in >> ox >> oy;
            expectKeyword(in, "NEAR");
            float nx, ny; in >> nx >> ny;
            expectKeyword(in, "WITHIN");
            float within; in >> within;

            const RingResult a = solveRing(poly, {ox, oy});
            const RingResult b = solveRing(poly, {nx, ny});
            float worst = 0.0f;
            for (std::size_t i = 0; i < a.w.size(); ++i) {
                worst = std::max(worst, std::fabs(a.w[i] - b.w[i]));
            }
            const bool ok = a.valid && b.valid && worst <= within;
            if (!ok) d << "on-edge and just-off-edge weights differ by "
                       << worst << ", more than " << within;
            record(cls, name, ok, d.str());

        } else if (kind == "NEGSWEEP") {
            // Measured, not described. Whether any interior point carries a
            // negative weight -- the property that decided non-convex regions
            // are accepted rather than refused.
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "ANYNEGATIVE");
            int want; in >> want;

            auto insideRing = [&](glm::vec2 p) {
                bool c = false;
                const std::size_t n = poly.size();
                for (std::size_t i = 0, j = n - 1; i < n; j = i++) {
                    if (((poly[i].y > p.y) != (poly[j].y > p.y)) &&
                        (p.x < (poly[j].x - poly[i].x) * (p.y - poly[i].y)
                               / (poly[j].y - poly[i].y) + poly[i].x)) {
                        c = !c;
                    }
                }
                return c;
            };
            bool anyNeg = false;
            const int steps = 120;
            for (int iy = 0; iy < steps && !anyNeg; ++iy) {
                for (int ix = 0; ix < steps && !anyNeg; ++ix) {
                    const glm::vec2 p(ix / float(steps - 1),
                                      iy / float(steps - 1));
                    if (!insideRing(p)) continue;
                    const RingResult r = solveRing(poly, p);
                    for (float w : r.w) {
                        if (w < -1e-6f) { anyNeg = true; break; }
                    }
                }
            }
            const bool ok = (anyNeg ? 1 : 0) == want;
            if (!ok) d << (want ? "expected negative weights inside this "
                                  "region and found none"
                                : "found a negative weight inside a region "
                                  "the reference says has none");
            record(cls, name, ok, d.str());

        } else if (kind == "CONSTRUCT") {
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "VALID");
            int want; in >> want;
            expectKeyword(in, "REASON");
            std::string wantReason; in >> wantReason;
            for (char& c : wantReason) if (c == '_') c = ' ';

            Manifold2D m; RegionID r;
            const bool made = build(poly, m, r);
            bool ok = (made ? 1 : 0) == want;
            if (!ok) {
                d << (want ? "expected the region to be accepted, refused: "
                               + m.lastRegionError()
                           : std::string("expected the region to be refused, "
                                         "it was accepted"));
            } else if (!made && wantReason != "none"
                       && m.lastRegionError().find(wantReason)
                              == std::string::npos) {
                // Right verdict, wrong reason is still a bug: it is the
                // message the author reads (DECISIONS.md D-007).
                ok = false;
                d << "refused for the wrong reason"
                  << "\n      expected: " << wantReason
                  << "\n      actual:   " << m.lastRegionError();
            }
            record(cls, name, ok, d.str());

        } else if (kind == "CONVEX") {
            expectKeyword(in, "POLY");
            const auto poly = readPoly(in);
            expectKeyword(in, "IS");
            int want; in >> want;
            Manifold2D m; RegionID r;
            if (!build(poly, m, r)) {
                record(cls, name, false, "region refused"); continue;
            }
            const TopologyReport rep = m.validate();
            const bool reported = !rep.nonConvex.empty();
            // Convexity is information and must never make a report unclean.
            bool ok = (m.region(r).convex() ? 1 : 0) == want
                   && reported == (want == 0)
                   && rep.clean();
            if (!ok) {
                d << "convex() " << m.region(r).convex()
                  << ", listed as non-convex " << reported
                  << ", clean() " << rep.clean()
                  << "\n      a non-convex region is information, never a "
                     "fault";
            }
            record(cls, name, ok, d.str());

        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass; fail += t.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
