// ofxManifold — conformance vector runner.
//
// Reads tests/vectors/triangle.vec, which is GENERATED by the independent
// Python reference in tests/ref/reference.py. Deliberately no JSON dependency:
// serialization is the last thing built (architecture doc §19), so the test
// harness must not force a format decision early.
//
// Exit code is 0 only if every vector passes. Per-class counts are reported
// separately, because the classes do not mean the same thing:
//
//   ANALYTIC  expected value known by hand from geometry. Failure means the
//             arithmetic is wrong. No appeal.
//   CROSS     expected value from the Python reference. Failure means the two
//             implementations disagree.
//   SPEC      expected value follows a rule we invented. Green means
//             self-consistent, NOT correct.
//
// A green run that is mostly SPEC has proved much less than a green run that is
// mostly ANALYTIC. The summary prints the split so that cannot be forgotten.

#include "../src/core/ofxManifoldTriangle.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally {
    int pass = 0;
    int fail = 0;
};

std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) {
        ++t.pass;
    } else {
        ++t.fail;
        failures.push_back(cls + "  " + name + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls
              << name << "\n";
}

bool close(float a, float b) {
    return std::fabs(a - b) <= tolerance;
}

std::string triple(float a, float b, float c) {
    std::ostringstream os;
    os << std::fixed << std::setprecision(9)
       << "(" << a << ", " << b << ", " << c << ")";
    return os.str();
}

// ---------------------------------------------------------------------------

void runTri(std::istringstream& in) {
    std::string name, cls;
    float ax, ay, bx, by, cx, cy, na, nb, nc, px, py, ea, eb, ec;
    in >> name >> cls >> ax >> ay >> bx >> by >> cx >> cy
       >> na >> nb >> nc >> px >> py >> ea >> eb >> ec;

    const glm::vec2 a{ax, ay}, b{bx, by}, c{cx, cy}, p{px, py};

    const BarycentricResult r = solveBiased(a, b, c, p, na, nb, nc);

    if (!r.valid) {
        record(cls, name, false, "solve reported invalid on a valid triangle");
        return;
    }

    const bool match = close(r.w[0], ea) && close(r.w[1], eb)
                    && close(r.w[2], ec);

    // Partition of unity is asserted for every row regardless of what the
    // expected values are. A solve that matched the reference but did not sum
    // to one would mean both implementations share a fault.
    const float sum = r.w[0] + r.w[1] + r.w[2];
    const bool unity = std::fabs(sum - 1.0f) <= tolerance;

    if (match && unity) {
        record(cls, name, true, "");
        return;
    }

    std::ostringstream d;
    if (!match) {
        d << "expected " << triple(ea, eb, ec)
          << "\n      got      " << triple(r.w[0], r.w[1], r.w[2]);
    }
    if (!unity) {
        if (!match) d << "\n      ";
        d << "weights sum to " << std::fixed << std::setprecision(12) << sum
          << ", not 1";
    }
    record(cls, name, false, d.str());
}

// Shared-edge agreement across two triangles. Needs two triangles in one
// assertion, hence its own record type.
void runPair(std::istringstream& in) {
    std::string name, cls;
    float ax, ay, bx, by, cx, cy, dx, dy, ex, ey, fx, fy, px, py;
    in >> name >> cls >> ax >> ay >> bx >> by >> cx >> cy
       >> dx >> dy >> ex >> ey >> fx >> fy >> px >> py;

    const glm::vec2 p{px, py};
    const BarycentricResult r1 =
        solveRaw({ax, ay}, {bx, by}, {cx, cy}, p);
    const BarycentricResult r2 =
        solveRaw({dx, dy}, {ex, ey}, {fx, fy}, p);

    if (!r1.valid || !r2.valid) {
        record(cls, name, false, "one of the paired triangles was degenerate");
        return;
    }

    // Triangle 1 is ABC, point on edge BC -> wA must vanish, and B, C are
    // coords 1 and 2. Triangle 2 is BCD, same point on edge BC -> wD must
    // vanish, and B, C are coords 0 and 1.
    const bool zero1 = close(r1.w[0], 0.0f);
    const bool zero2 = close(r2.w[2], 0.0f);
    const bool agreeB = close(r1.w[1], r2.w[0]);
    const bool agreeC = close(r1.w[2], r2.w[1]);

    if (zero1 && zero2 && agreeB && agreeC) {
        record(cls, name, true, "");
        return;
    }

    std::ostringstream d;
    d << "ABC " << triple(r1.w[0], r1.w[1], r1.w[2])
      << "\n      BCD " << triple(r2.w[0], r2.w[1], r2.w[2]);
    if (!zero1)  d << "\n      opposite vertex A did not vanish";
    if (!zero2)  d << "\n      opposite vertex D did not vanish";
    if (!agreeB) d << "\n      triangles disagree on shared node B";
    if (!agreeC) d << "\n      triangles disagree on shared node C";
    record(cls, name, false, d.str());
}

// Degenerate triangles must be refused at construction, not evaluated.
void runDegenerate(std::istringstream& in) {
    std::string name, cls;
    float ax, ay, bx, by, cx, cy;
    in >> name >> cls >> ax >> ay >> bx >> by >> cx >> cy;

    Triangle t;
    const bool made = Triangle::make(0, 1, 2, {ax, ay}, {bx, by}, {cx, cy}, t);

    if (!made) {
        record(cls, name, true, "");
        return;
    }
    record(cls, name, false,
           "Triangle::make accepted a degenerate triangle; it must be "
           "rejected at construction so the solve never sees it");
}

// A triangle above the construction epsilon must be ACCEPTED. Without this,
// the degeneracy check is one-sided: an implementation that rejected every
// triangle would pass every DEGENERATE row. These rows are what make
// kAreaEpsilon a threshold rather than a floor.
void runAccept(std::istringstream& in) {
    std::string name, cls;
    float ax, ay, bx, by, cx, cy;
    in >> name >> cls >> ax >> ay >> bx >> by >> cx >> cy;

    Triangle t;
    const bool made = Triangle::make(0, 1, 2, {ax, ay}, {bx, by}, {cx, cy}, t);

    if (made) {
        // Construction succeeding is not enough on its own: the retained
        // winding sign is what the animated-position flip test in section 8.6
        // compares against, so a sign of zero would be a silent hole.
        if (t.constructionSign() == 0) {
            record(cls, name, false,
                   "accepted, but constructionSign() is 0; the section 8.6 "
                   "flip test would have nothing to compare against");
            return;
        }
        record(cls, name, true, "");
        return;
    }

    std::ostringstream d;
    const float area2 = signedArea2({ax, ay}, {bx, by}, {cx, cy});
    d << "Triangle::make rejected a valid triangle; doubled area is "
      << std::scientific << std::setprecision(6) << area2
      << ", kAreaEpsilon is " << kAreaEpsilon
      << "\n      raising the epsilon has begun eating legitimate topology";
    record(cls, name, false, d.str());
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/triangle.vec";

    std::ifstream f(path);
    if (!f) {
        std::cerr << "cannot open vector file: " << path << "\n";
        return 2;
    }

    std::cout << "ofxManifold triangle kernel\n"
              << "vectors: " << path << "\n\n";

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') {
            continue;
        }
        std::istringstream in(line);
        std::string kind;
        in >> kind;

        if (kind == "TOL") {
            in >> tolerance;
        } else if (kind == "TRI") {
            runTri(in);
        } else if (kind == "PAIR") {
            runPair(in);
        } else if (kind == "DEGENERATE") {
            runDegenerate(in);
        } else if (kind == "ACCEPT") {
            runAccept(in);
        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass;
        fail += t.fail;
    }

    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) {
            std::cout << "  " << s << "\n";
        }
    }

    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");

    if (fail == 0) {
        std::cout << "\nnote: SPEC vectors assert a rule we invented. They "
                     "show self-consistency,\n      not correctness. Only "
                     "ANALYTIC and CROSS carry outside authority.\n";
    }

    return fail == 0 ? 0 : 1;
}
