// ofxManifold — mapping layer conformance vector runner.
//
// Reads tests/vectors/mapping.vec, generated by the independent Python
// reference in tests/ref/reference_mapping.py, which inverts the C++'s loop:
// it indexes target -> contributions and pulls, where the C++ iterates nodes
// and pushes.
//
// Targets are compared BY NAME throughout, never by position. See D-004.

#include "../src/mapping/ofxManifoldMapping.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;
std::string fixtureName;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + fixtureName + " / " + name
                           + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls
              << std::setw(18) << fixtureName << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

WeightVector readWeights(std::istringstream& in) {
    WeightVector v;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        const std::size_t eq = tok.find('=');
        if (eq == std::string::npos) { in.clear(); in.seekg(mark); break; }
        v.push_back(WeightedNode{
            static_cast<NodeID>(std::stoul(tok.substr(0, eq))),
            std::stof(tok.substr(eq + 1))});
    }
    return v;
}

void expectKeyword(std::istringstream& in, const char* kw) {
    std::string tok;
    in >> tok;
    if (tok != kw) {
        std::cerr << "malformed vector: expected " << kw << ", saw " << tok
                  << "\n";
        std::exit(2);
    }
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/mapping.vec";
    std::ifstream f(path);
    if (!f) { std::cerr << "cannot open vector file: " << path << "\n"; return 2; }

    std::cout << "ofxManifold mapping\nvectors: " << path << "\n\n";

    Mapping mp;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind;
        in >> kind;

        if (kind == "TOL") { in >> tolerance; continue; }
        if (kind == "MAPPING") { mp = Mapping{}; in >> fixtureName; continue; }
        if (kind == "END") continue;

        if (kind == "TARGET") {
            std::string n; in >> n; mp.addTarget(n); continue;
        }
        if (kind == "BIND") {
            NodeID node; std::string tname; float w;
            in >> node >> tname >> w;
            mp.bind(node, mp.addTarget(tname), w);
            continue;
        }
        if (kind == "AGGREGATOR") {
            std::string n, mode; in >> n >> mode;
            std::vector<NodeID> srcs; NodeID s;
            while (in >> s) srcs.push_back(s);
            mp.addAggregator(n, srcs,
                             mode == "power" ? SumMode::PowerPreserving
                                             : SumMode::Linear);
            continue;
        }

        std::string name, cls;
        in >> name >> cls;
        std::ostringstream d;

        if (kind == "RESOLVE") {
            expectKeyword(in, "IN");
            const WeightVector input = readWeights(in);
            expectKeyword(in, "OUT");
            // Expected pairs are target NAME = weight.
            std::vector<std::pair<std::string, float>> want;
            std::string tok;
            while (in >> tok) {
                const std::size_t eq = tok.find('=');
                if (eq == std::string::npos) continue;
                want.emplace_back(tok.substr(0, eq),
                                  std::stof(tok.substr(eq + 1)));
            }
            const Resolved r = mp.resolve(input);

            bool ok = r.targets.size() == want.size();
            if (!ok) {
                d << "expected " << want.size() << " targets, got "
                  << r.targets.size();
                for (const auto& t : r.targets) {
                    d << "\n      got " << mp.targetName(t.id) << "="
                      << std::fixed << std::setprecision(9) << t.weight;
                }
            } else {
                for (const auto& wt : want) {
                    const TargetID id = mp.findTarget(wt.first);
                    bool found = false;
                    for (const auto& t : r.targets) {
                        if (t.id != id) continue;
                        found = true;
                        if (!close(t.weight, wt.second)) {
                            ok = false;
                            d << "\n      target " << wt.first << ": expected "
                              << std::fixed << std::setprecision(9)
                              << wt.second << ", got " << t.weight;
                        }
                        break;
                    }
                    if (!found) {
                        ok = false;
                        d << "\n      target " << wt.first << " missing";
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "DENSE") {
            expectKeyword(in, "IN");
            const WeightVector input = readWeights(in);
            expectKeyword(in, "OUT");
            std::vector<float> want; float x;
            while (in >> x) want.push_back(x);

            const std::vector<float> got = mp.toDenseVector(input);
            bool ok = got.size() == want.size();
            if (!ok) {
                d << "dense arity: expected " << want.size() << ", got "
                  << got.size()
                  << "\n      arity must equal the target count regardless of"
                     " the point";
            } else {
                for (std::size_t i = 0; i < want.size(); ++i) {
                    if (!close(got[i], want[i])) {
                        ok = false;
                        d << "\n      slot " << i << " ("
                          << mp.targetName(static_cast<TargetID>(i))
                          << "): expected " << std::fixed
                          << std::setprecision(9) << want[i] << ", got "
                          << got[i];
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "TARGETSUM") {
            expectKeyword(in, "IN");
            const WeightVector input = readWeights(in);
            expectKeyword(in, "SUM");
            float want; in >> want;
            const Resolved r = mp.resolve(input);
            float got = 0.0f;
            for (const auto& t : r.targets) got += t.weight;
            const bool ok = close(got, want);
            if (!ok) d << "expected total " << std::fixed
                       << std::setprecision(9) << want << ", got " << got;
            record(cls, name, ok, d.str());

        } else if (kind == "AGGREGATE") {
            expectKeyword(in, "IN");
            const WeightVector input = readWeights(in);
            expectKeyword(in, "OUT");
            std::vector<float> want; float x;
            while (in >> x) want.push_back(x);

            const Resolved r = mp.resolve(input);
            bool ok = r.aggregates.size() == want.size();
            if (!ok) {
                d << "expected " << want.size() << " aggregates, got "
                  << r.aggregates.size();
            } else {
                for (std::size_t i = 0; i < want.size(); ++i) {
                    if (!close(r.aggregates[i], want[i])) {
                        ok = false;
                        d << "\n      aggregator "
                          << mp.aggregators()[i].name << ": expected "
                          << std::fixed << std::setprecision(9) << want[i]
                          << ", got " << r.aggregates[i];
                    }
                }
            }
            record(cls, name, ok, d.str());

        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass; fail += t.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
