// ofxManifold — interpretation layer conformance vector runner.
//
// Reads tests/vectors/interpretation.vec, generated by the independent Python
// reference in tests/ref/reference_interpretation.py.
//
// Every operation here is a pure function over weight vectors, so there is no
// manifold and no geometry in this file. That is the layer boundary being
// exercised, not just described.

#include "../src/interpretation/ofxManifoldBlend.h"
#include "../src/interpretation/ofxManifoldSpread.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + name + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

curve::Fn curveByName(const std::string& n) {
    if (n == "linear")     return curve::linear;
    if (n == "equalPower") return curve::equalPower;
    if (n == "cosine")     return curve::cosine;
    return nullptr;
}

// Reads `id=weight` tokens until a keyword or end of line.
WeightVector readVector(std::istringstream& in) {
    WeightVector v;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        const std::size_t eq = tok.find('=');
        if (eq == std::string::npos) {
            in.clear();
            in.seekg(mark);       // put the keyword back
            break;
        }
        v.push_back(WeightedNode{
            static_cast<NodeID>(std::stoul(tok.substr(0, eq))),
            std::stof(tok.substr(eq + 1))});
    }
    return v;
}

std::string show(const WeightVector& v) {
    std::ostringstream os;
    os << std::fixed << std::setprecision(9);
    for (const auto& wn : v) os << " " << wn.id << "=" << wn.weight;
    return os.str();
}

// Compares by NODE ID, not by position. An implementation that produced the
// right numbers against the wrong nodes would pass a positional check and be
// wrong in the room.
bool sameVector(const WeightVector& got, const WeightVector& want,
                std::ostringstream& d) {
    if (got.size() != want.size()) {
        d << "expected " << want.size() << " entries, got " << got.size()
          << "\n      expected" << show(want)
          << "\n      got     " << show(got);
        return false;
    }
    bool ok = true;
    for (const auto& w : want) {
        bool found = false;
        for (const auto& g : got) {
            if (g.id != w.id) continue;
            found = true;
            if (!close(g.weight, w.weight)) {
                ok = false;
                d << "\n      node " << w.id << ": expected "
                  << std::fixed << std::setprecision(9) << w.weight
                  << ", got " << g.weight;
            }
            break;
        }
        if (!found) {
            ok = false;
            d << "\n      node " << w.id << " missing from result";
        }
    }
    return ok;
}

void expectKeyword(std::istringstream& in, const char* kw) {
    std::string tok;
    in >> tok;
    if (tok != kw) {
        std::cerr << "malformed vector: expected " << kw << ", saw " << tok
                  << "\n";
        std::exit(2);
    }
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/interpretation.vec";

    std::ifstream f(path);
    if (!f) {
        std::cerr << "cannot open vector file: " << path << "\n";
        return 2;
    }

    std::cout << "ofxManifold interpretation\n"
              << "vectors: " << path << "\n\n";

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind;
        in >> kind;

        if (kind == "TOL") { in >> tolerance; continue; }

        std::string name, cls;
        in >> name >> cls;
        std::ostringstream d;

        if (kind == "CURVE") {
            std::string cname; in >> cname;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "OUT");
            const WeightVector want = readVector(in);
            const WeightVector got = curve::apply(input, curveByName(cname));
            record(cls, name, sameVector(got, want, d), d.str());

        } else if (kind == "POWER") {
            std::string cname; in >> cname;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "SUMSQ");
            float want; in >> want;
            const float got = power(curve::apply(input, curveByName(cname)));
            const bool ok = close(got, want);
            if (!ok) d << "expected sum of squares " << std::fixed
                       << std::setprecision(9) << want << ", got " << got;
            record(cls, name, ok, d.str());

        } else if (kind == "SUM") {
            std::string cname; in >> cname;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "SUM");
            float want; in >> want;
            const float got = sum(curve::apply(input, curveByName(cname)));
            const bool ok = close(got, want);
            if (!ok) d << "expected sum " << std::fixed << std::setprecision(9)
                       << want << ", got " << got
                       << "\n      a curve must not renormalize";
            record(cls, name, ok, d.str());

        } else if (kind == "NORMALIZE") {
            std::string cname; in >> cname;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "OUT");
            const WeightVector want = readVector(in);
            const WeightVector got =
                normalize(curve::apply(input, curveByName(cname)));
            bool ok = sameVector(got, want, d);
            if (ok && !close(sum(got), 1.0f)) {
                ok = false;
                d << "normalize() did not produce a sum of one";
            }
            record(cls, name, ok, d.str());

        } else if (kind == "SPREAD") {
            float amount; std::size_t total;
            in >> amount >> total;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "OUT");
            const WeightVector want = readVector(in);
            const WeightVector got = spread(input, amount, total);
            record(cls, name, sameVector(got, want, d), d.str());

        } else if (kind == "SPREADSUM") {
            float amount; std::size_t total;
            in >> amount >> total;
            expectKeyword(in, "IN");
            const WeightVector input = readVector(in);
            expectKeyword(in, "SUM");
            float want; in >> want;
            const float got = sum(spread(input, amount, total));
            const bool ok = close(got, want);
            if (!ok) d << "expected sum " << std::fixed << std::setprecision(9)
                       << want << ", got " << got
                       << "\n      spread must preserve partition of unity";
            record(cls, name, ok, d.str());

        } else if (kind == "BLEND") {
            float t; std::string cname;
            in >> t >> cname;
            expectKeyword(in, "A");
            const WeightVector a = readVector(in);
            expectKeyword(in, "B");
            const WeightVector b = readVector(in);
            expectKeyword(in, "OUT");
            const WeightVector want = readVector(in);
            const WeightVector got = blend(a, b, t, curveByName(cname));
            record(cls, name, sameVector(got, want, d), d.str());

        } else if (kind == "BLENDSUM") {
            float t; std::string cname;
            in >> t >> cname;
            expectKeyword(in, "A");
            const WeightVector a = readVector(in);
            expectKeyword(in, "B");
            const WeightVector b = readVector(in);
            expectKeyword(in, "SUM");
            float want; in >> want;
            const float got = sum(blend(a, b, t, curveByName(cname)));
            const bool ok = close(got, want);
            if (!ok) d << "expected sum " << std::fixed << std::setprecision(9)
                       << want << ", got " << got;
            record(cls, name, ok, d.str());

        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass;
        fail += t.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
