// ofxManifold — outputs conformance vector runner (PLAN-outputs.md).
//
// Reads tests/vectors/outputs.vec, generated by tests/ref/reference_outputs.py.
// The reference resolves per DESTINATION and computes silence directly; the
// C++ accumulates per node. They agree only if silence really is the
// complement of routing.

#include "../src/io/ofxManifoldSerialize.h"

#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
float tolerance = 1e-6f;
std::string fixtureDir = "tests/fixtures";
std::map<std::string, Mapping> maps;

void record(const std::string& cls, const std::string& name, bool ok,
            const std::string& detail) {
    Tally& t = tallies[cls];
    if (ok) ++t.pass; else {
        ++t.fail;
        failures.push_back(cls + "  " + name + "\n      " + detail);
    }
    std::cout << (ok ? "  pass  " : "  FAIL  ")
              << std::left << std::setw(10) << cls << name << "\n";
}

bool close(float a, float b) { return std::fabs(a - b) <= tolerance; }

bool isNumber(const std::string& t) {
    if (t.empty()) return false;
    char* end = nullptr;
    std::strtod(t.c_str(), &end);
    return end && *end == '\0';
}

void expectKeyword(std::istringstream& in, const char* kw) {
    std::string tok; in >> tok;
    if (tok != kw) {
        std::cerr << "malformed vector: expected " << kw << ", saw " << tok
                  << "\n";
        std::exit(2);
    }
}

// Numbers until the next keyword.
std::vector<float> readFloats(std::istringstream& in) {
    std::vector<float> v;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        if (!isNumber(tok)) { in.clear(); in.seekg(mark); break; }
        v.push_back(std::stof(tok));
    }
    return v;
}

// "n=w ..." until the next keyword, or "NONE".
WeightVector readWeights(std::istringstream& in) {
    WeightVector w;
    std::streampos mark;
    std::string tok;
    while (true) {
        mark = in.tellg();
        if (!(in >> tok)) break;
        if (tok == "NONE") continue;
        const std::size_t eq = tok.find('=');
        if (eq == std::string::npos) { in.clear(); in.seekg(mark); break; }
        w.push_back(WeightedNode{NodeID(std::stoul(tok.substr(0, eq))),
                                 std::stof(tok.substr(eq + 1))});
    }
    return w;
}

bool sameFloats(const std::vector<float>& got, const std::vector<float>& want,
                const char* what, std::ostringstream& d) {
    if (got.size() != want.size()) {
        d << what << ": expected " << want.size() << " entries, got "
          << got.size();
        return false;
    }
    for (std::size_t i = 0; i < want.size(); ++i) {
        if (!close(got[i], want[i])) {
            d << what << "[" << i << "]: expected " << std::fixed
              << std::setprecision(6) << want[i] << ", got " << got[i];
            return false;
        }
    }
    return true;
}

bool slurp(const std::string& file, std::string& out) {
    std::ifstream f(fixtureDir + "/" + file);
    if (!f) return false;
    std::ostringstream ss; ss << f.rdbuf(); out = ss.str();
    return true;
}

bool loadManifoldFixture(const std::string& file, Manifold2D& m) {
    std::string text;
    return slurp(file, text) && io::loadManifold(text, m).ok;
}

std::string kindName(NodeKind k) {
    switch (k) {
    case NodeKind::Null:      return "null";
    case NodeKind::Terminal:  return "terminal";
    case NodeKind::Composite: return "composite";
    case NodeKind::Partial:   return "partial";
    }
    return "?";
}

int savedVersion(const std::string& text) {
    const std::size_t p = text.find("\"version\": ");
    return p == std::string::npos ? -1 : std::atoi(text.c_str() + p + 11);
}

// Probe weight vectors over nodes 0..5, for comparing two mappings.
std::vector<WeightVector> probes() {
    return {
        {{0, 1.0f}},
        {{1, 1.0f}},
        {{0, 0.5f}, {1, 0.3f}, {2, 0.2f}},
        {{2, 0.4f}, {3, 0.35f}, {4, 0.25f}},
        {{0, 0.2f}, {1, 0.2f}, {2, 0.2f}, {3, 0.2f}, {4, 0.1f}, {5, 0.1f}},
    };
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/outputs.vec";
    if (argc > 2) fixtureDir = argv[2];
    std::ifstream f(path);
    if (!f) { std::cerr << "cannot open: " << path << "\n"; return 2; }

    std::cout << "ofxManifold outputs\nvectors: " << path << "\n\n";

    std::string current;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind; in >> kind;
        if (kind == "TOL") { in >> tolerance; continue; }

        // ---- building mappings, replayed through the C++ API -------------
        if (kind == "MAP") { in >> current; maps[current] = Mapping(); continue; }
        if (kind == "ENDMAP") { current.clear(); continue; }
        if (kind == "TARGET") {
            // The OLD way, so the legacy records test the path existing code
            // actually takes.
            std::string nm; in >> nm;
            maps[current].addTarget(nm);
            continue;
        }
        if (kind == "OUT") {
            std::string nm; int ch; float tr;
            in >> nm >> ch >> tr;
            if (maps[current].addOutput(nm, ch, tr) == InvalidTarget) {
                std::cerr << "fixture output refused: " << nm << "\n";
                return 2;
            }
            continue;
        }
        if (kind == "BIND") {
            unsigned node; std::string what;
            in >> node >> what;
            Mapping& mp = maps[current];
            if (what == "OUTPUT") {
                std::string dest; float w; in >> dest >> w;
                mp.bind(NodeID(node), mp.findTarget(dest), w);
            } else {
                float w; in >> w;
                mp.bindSilence(NodeID(node), w);
            }
            continue;
        }
        if (kind == "DERIVED") {
            std::string nm, mode; int ch; float tr;
            in >> nm >> ch >> tr >> mode;
            expectKeyword(in, "SRC");
            std::vector<std::pair<NodeID, float>> srcs;
            std::string tok;
            while (in >> tok) {
                const std::size_t c = tok.find(':');
                srcs.emplace_back(NodeID(std::stoul(tok.substr(0, c))),
                                  std::stof(tok.substr(c + 1)));
            }
            if (maps[current].addDerived(nm, ch, tr,
                    mode == "power" ? SumMode::PowerPreserving
                                    : SumMode::Linear, srcs)
                    == static_cast<std::size_t>(-1)) {
                std::cerr << "fixture derived refused: " << nm << "\n";
                return 2;
            }
            continue;
        }

        std::string name, cls; in >> name >> cls;
        std::ostringstream d;

        if (kind == "LEGACY") {
            expectKeyword(in, "MAP");
            std::string mn; in >> mn;
            expectKeyword(in, "IN");
            const WeightVector w = readWeights(in);
            expectKeyword(in, "DENSE");
            const std::vector<float> want = readFloats(in);
            const Mapping& mp = maps[mn];
            bool ok = sameFloats(mp.toChannels(w), want, "toChannels", d);
            // THE claim: for a mapping built the old way, the new channel
            // vector IS the existing dense vector -- checked against the C++
            // toDenseVector() itself, not only the reference's numbers.
            if (ok) ok = sameFloats(mp.toChannels(w), mp.toDenseVector(w),
                                    "toChannels vs toDenseVector", d);
            record(cls, name, ok, d.str());

        } else if (kind == "RESOLVE" || kind == "REMAP") {
            expectKeyword(in, "MAP");
            std::string mn; in >> mn;
            Mapping mp = maps[mn];
            if (kind == "REMAP") {
                expectKeyword(in, "TABLE");
                std::vector<NodeID> table;
                for (float t : readFloats(in)) {
                    table.push_back(t < 0 ? InvalidNode : NodeID(t));
                }
                mp.remapNodes(table);
            }
            expectKeyword(in, "IN");
            const WeightVector w = readWeights(in);
            expectKeyword(in, "ROUTED");
            const std::vector<float> routed = readFloats(in);
            expectKeyword(in, "SILENCE");
            float silence; in >> silence;
            expectKeyword(in, "LEVELS");
            const std::vector<float> levels = readFloats(in);

            bool ok = sameFloats(mp.toChannels(w), routed, "routed", d);
            if (ok && !close(mp.silenceShare(w), silence)) {
                ok = false;
                d << "silence: expected " << silence << ", got "
                  << mp.silenceShare(w);
            }
            if (ok) ok = sameFloats(mp.toChannelLevels(w), levels, "levels", d);
            // Routed outputs plus silence account for the whole input.
            if (ok) {
                float in_ = 0.0f, out_ = 0.0f;
                for (const auto& wn : w) in_ += wn.weight;
                for (const auto& t : mp.resolve(w).targets) out_ += t.weight;
                if (!close(out_ + mp.silenceShare(w), in_)) {
                    ok = false;
                    d << "outputs " << out_ << " + silence "
                      << mp.silenceShare(w) << " != input " << in_
                      << " -- silence is not the complement of routing";
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "REFUSE") {
            // Every operation but the last must succeed; the last must fail.
            std::vector<std::pair<std::string, std::pair<std::string, int>>> ops;
            std::string op;
            while (in >> op) {
                std::string nm; int ch; in >> nm >> ch;
                ops.push_back({op, {nm, ch}});
            }
            Mapping mp;
            bool ok = true;
            for (std::size_t i = 0; i < ops.size() && ok; ++i) {
                const bool last = (i + 1 == ops.size());
                bool made;
                if (ops[i].first == "OUTPUT") {
                    made = mp.addOutput(ops[i].second.first,
                                        ops[i].second.second) != InvalidTarget;
                } else {
                    made = mp.addDerived(ops[i].second.first,
                                         ops[i].second.second, 1.0f,
                                         SumMode::Linear, {})
                           != static_cast<std::size_t>(-1);
                }
                if (made == last) {
                    ok = false;
                    d << (last ? "the last operation should have been refused"
                               : "an earlier operation was refused");
                }
            }
            record(cls, name, ok, d.str());

        } else if (kind == "LABEL") {
            expectKeyword(in, "MAP");
            std::string mn; in >> mn;
            expectKeyword(in, "NODE");
            unsigned node; in >> node;
            expectKeyword(in, "EXPECT");
            std::string want; in >> want;
            expectKeyword(in, "FRACTION");
            float frac; in >> frac;
            const Mapping& mp = maps[mn];
            const std::string got = kindName(mp.nodeKind(NodeID(node)));
            bool ok = (got == want) && close(mp.outputFraction(NodeID(node)), frac);
            if (!ok) d << "expected " << want << " " << frac << ", got " << got
                       << " " << mp.outputFraction(NodeID(node));
            record(cls, name, ok, d.str());

        } else if (kind == "MAPPRESERVE") {
            // Everything must survive a save and reload -- the check the L/R
            // swap and the dropped unbound output would have failed.
            expectKeyword(in, "MAP");
            std::string mn; in >> mn;
            expectKeyword(in, "MANIFOLD");
            std::string mf; in >> mf;
            expectKeyword(in, "VERSION");
            int wantVer; in >> wantVer;

            Manifold2D m;
            if (!loadManifoldFixture(mf, m)) {
                record(cls, name, false, "cannot load " + mf); continue;
            }
            const Mapping& a = maps[mn];
            const std::string s1 = io::saveMapping(a, m);
            Mapping b;
            const io::LoadResult r = io::loadMapping(s1, m, b);
            bool ok = r.ok;
            if (!ok) d << "reload failed: " << r.error;
            if (ok && savedVersion(s1) != wantVer) {
                ok = false;
                d << "written as version " << savedVersion(s1)
                  << ", expected " << wantVer;
            }
            if (ok && a.targetCount() != b.targetCount()) {
                ok = false;
                d << a.targetCount() << " outputs before, " << b.targetCount()
                  << " after -- an output was lost";
            }
            for (TargetID t = 0; ok && t < a.targetCount(); ++t) {
                if (a.targetName(t) != b.targetName(t)
                    || a.targetChannel(t) != b.targetChannel(t)
                    || !close(a.targetTrim(t), b.targetTrim(t))) {
                    ok = false;
                    d << "output " << t << " was " << a.targetName(t) << " ch "
                      << a.targetChannel(t) << ", reloaded as "
                      << b.targetName(t) << " ch " << b.targetChannel(t);
                }
            }
            if (ok && a.aggregators().size() != b.aggregators().size()) {
                ok = false;
                d << "derived output count changed";
            }
            for (const WeightVector& w : probes()) {
                if (!ok) break;
                ok = sameFloats(b.toChannelLevels(w), a.toChannelLevels(w),
                                "levels after reload", d)
                  && close(a.silenceShare(w), b.silenceShare(w));
                if (!ok && d.str().empty()) d << "silence changed on reload";
                if (ok) {
                    const std::vector<float> da = a.toDenseVector(w);
                    const std::vector<float> db = b.toDenseVector(w);
                    ok = sameFloats(db, da, "dense vector after reload", d);
                }
            }
            if (ok && io::saveMapping(b, m) != s1) {
                ok = false;
                d << "second save differs from the first";
            }
            record(cls, name, ok, d.str());

        } else if (kind == "MAPFILE") {
            std::string mf, file, verdict;
            in >> mf >> file >> verdict;
            Manifold2D m;
            if (!loadManifoldFixture(mf, m)) {
                record(cls, name, false, "cannot load " + mf); continue;
            }
            std::string text;
            if (!slurp(file, text)) {
                record(cls, name, false, "missing " + file); continue;
            }
            Mapping mp;
            const io::LoadResult r = io::loadMapping(text, m, mp);
            bool ok;
            if (verdict == "OK") {
                ok = r.ok;
                if (!ok) d << "expected to load: " << r.error;
            } else {
                std::string reason; in >> reason;
                ok = !r.ok && r.error.find(reason) != std::string::npos;
                if (r.ok) d << "expected refusal, it loaded";
                else if (!ok) d << "refused for the wrong reason"
                                << "\n      expected the error to mention: "
                                << reason << "\n      actual: " << r.error;
            }
            record(cls, name, ok, d.str());

        } else if (kind == "MAPROUNDTRIP") {
            std::string mf, file; in >> mf >> file;
            Manifold2D m; std::string text;
            if (!loadManifoldFixture(mf, m) || !slurp(file, text)) {
                record(cls, name, false, "missing fixture"); continue;
            }
            Mapping a, b;
            bool ok = io::loadMapping(text, m, a).ok;
            const std::string s1 = ok ? io::saveMapping(a, m) : "";
            ok = ok && io::loadMapping(s1, m, b).ok;
            const std::string s2 = ok ? io::saveMapping(b, m) : "";
            ok = ok && s1 == s2 && savedVersion(s1) == 2;
            if (!ok) d << "save -> load -> save is not byte-stable, or not v2";
            record(cls, name, ok, d.str());

        } else if (kind == "MAPVERSION") {
            std::string mf, src; int want;
            in >> mf >> src >> want;
            Manifold2D m;
            if (!loadManifoldFixture(mf, m)) {
                record(cls, name, false, "cannot load " + mf); continue;
            }
            Mapping mp;
            if (src == "LEGACYMAP") {
                mp = maps["legacy"];
            } else {
                std::string text;
                if (!slurp(src, text) || !io::loadMapping(text, m, mp).ok) {
                    record(cls, name, false, "cannot load " + src); continue;
                }
            }
            const int got = savedVersion(io::saveMapping(mp, m));
            const bool ok = (got == want);
            if (!ok) d << "written as version " << got << ", expected " << want;
            record(cls, name, ok, d.str());

        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const char* cls : {"ANALYTIC", "CROSS", "SPEC"}) {
        const Tally& t = tallies[cls];
        if (t.pass + t.fail == 0) continue;
        std::cout << "  " << std::left << std::setw(10) << cls
                  << t.pass << "/" << (t.pass + t.fail) << "\n";
        pass += t.pass; fail += t.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
