// ofxManifoldEditor — model conformance vector runner.
//
// Reads tests/vectors/editor.vec, generated by tests/ref/reference_editor.py.
// Each EDIT block is a script: operations applied to editor::Model through the
// same calls an editor makes, with the Result and the complete state checked
// after every one. The reference tracks everything by name; the model tracks
// ids and renumbers on every delete.

#include "ofxManifoldEditorModel.h"
#include "ofxManifoldEditorSelection.h"
#include "ofxManifoldEditorChartLayout.h"
#include "ofxManifoldEditorHistory.h"

#include <functional>

#include <cctype>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace ofxManifold;
using namespace ofxManifold::editor;

namespace {

struct Tally { int pass = 0; int fail = 0; };
std::map<std::string, Tally> tallies;
std::vector<std::string> failures;
double tolerance = 1e-5;

std::string num(double v) {
    char b[32];
    std::snprintf(b, sizeof b, "%.6g", v);
    return b;
}

// The model's state in the reference's canonical form.
std::string dump(const Model& md) {
    const Manifold2D& m = md.manifold();
    const Mapping& mp = md.mapping();
    std::ostringstream o;
    o << "N";
    for (NodeID i = 0; i < m.nodeCount(); ++i) {
        o << " " << m.node(i).name << "@" << num(m.node(i).position.x) << ","
          << num(m.node(i).position.y);
    }
    o << " | R";
    for (RegionID r = 0; r < m.regionCount(); ++r) {
        o << " ";
        const auto& ids = m.region(r).ids();
        for (std::size_t k = 0; k < ids.size(); ++k) {
            o << (k ? "," : "") << m.node(ids[k]).name;
        }
    }
    o << " | O";
    for (TargetID t = 0; t < mp.targetCount(); ++t) {
        o << " " << mp.targetName(t) << ":" << mp.targetChannel(t) << ":"
          << num(mp.targetTrim(t));
    }
    o << " | L";
    for (NodeID i = 0; i < m.nodeCount(); ++i) {
        for (std::size_t k = 0; k < mp.linkCount(i); ++k) {
            const Link& l = mp.link(i, k);
            o << " " << m.node(i).name << ">"
              << (l.kind == DestKind::Output ? mp.targetName(l.id)
                                             : std::string("~"))
              << ":" << num(l.weight);
        }
    }
    o << " | D";
    for (const auto& a : mp.aggregators()) {
        o << " " << a.name << ":" << a.channel << ":";
        for (std::size_t k = 0; k < a.sources.size(); ++k) {
            o << (k ? "," : "") << m.node(a.sources[k]).name;
        }
    }
    o << " | C " << (md.currentOutput() == InvalidTarget
                     ? std::string("-") : mp.targetName(md.currentOutput()));
    o << " | A " << (md.autoOutput() ? "1" : "0");
    return o.str();
}

// Split into number runs and everything else, so numbers compare within
// tolerance and names compare exactly.
std::vector<std::string> tokens(const std::string& s) {
    std::vector<std::string> t;
    std::size_t i = 0;
    while (i < s.size()) {
        if (std::isspace(static_cast<unsigned char>(s[i]))) { ++i; continue; }
        std::size_t j = i;
        if (std::isdigit(static_cast<unsigned char>(s[i])) || s[i] == '.') {
            while (j < s.size() && (std::isdigit(static_cast<unsigned char>(s[j]))
                                    || s[j] == '.' || s[j] == 'e'
                                    || ((s[j] == '-' || s[j] == '+')
                                        && j > i && s[j - 1] == 'e'))) ++j;
        } else {
            ++j;
        }
        t.push_back(s.substr(i, j - i));
        i = j;
    }
    return t;
}

bool isNum(const std::string& t) {
    return !t.empty() && (std::isdigit(static_cast<unsigned char>(t[0]))
                          || t[0] == '.');
}

bool sameState(const std::string& want, const std::string& got) {
    const auto a = tokens(want), b = tokens(got);
    if (a.size() != b.size()) return false;
    for (std::size_t i = 0; i < a.size(); ++i) {
        if (isNum(a[i]) && isNum(b[i])) {
            if (std::fabs(std::stod(a[i]) - std::stod(b[i])) > tolerance) {
                return false;
            }
        } else if (a[i] != b[i]) {
            return false;
        }
    }
    return true;
}

Grid readGrid(std::istringstream& in) {
    std::string kind; in >> kind;
    if (kind == "LATTICE") {
        float ux, uy, vx, vy, ox, oy, a;
        in >> ux >> uy >> vx >> vy >> ox >> oy >> a;
        return Grid::lattice({ux, uy}, {vx, vy}, {ox, oy}, a);
    }
    if (kind == "POLAR") {
        float cx, cy, dr, a; int sp;
        in >> cx >> cy >> dr >> sp >> a;
        return Grid::polar({cx, cy}, dr, sp, a);
    }
    return Grid::free();
}

// The label each operation is recorded under -- the same words the reference
// uses, so an undo message naming the wrong action fails a vector.
std::string label(const std::string& op) {
    static const std::map<std::string, std::string> L = {
        {"place", "place"}, {"join", "join"}, {"unjoin", "unjoin"},
        {"remove", "delete"}, {"newoutput", "new output"},
        {"derived", "derived output"}, {"bind", "binding"},
        {"bindall", "bind to every output"}, {"fill", "fill"},
        {"clear", "clear bindings"}, {"trim", "trim"},
        {"removeoutput", "remove output"}, {"example", "example map"},
        {"empty", "new map"}, {"move", "move"}};
    auto it = L.find(op);
    return it == L.end() ? op : it->second;
}

} // namespace

int main(int argc, char** argv) {
    const std::string path =
        (argc > 1) ? argv[1] : "tests/vectors/editor.vec";
    std::ifstream f(path);
    if (!f) { std::cerr << "cannot open: " << path << "\n"; return 2; }
    std::cout << "ofxManifoldEditor model\nvectors: " << path << "\n\n";

    std::string name, cls, lastOp;
    Model md;
    Selection sel;
    Grid grid;
    Result last;
    History hist;
    ChartLayout layout;
    float chX = 0, chTop = 0, chW = 0, chH = 0;
    bool ok = true;
    std::ostringstream why;
    int step = 0;

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream in(line);
        std::string kind; in >> kind;
        if (kind == "TOL") { in >> tolerance; continue; }

        if (kind == "EDIT") {
            in >> name >> cls;
            md = Model();
            hist = History();
            sel.clear();
            grid = Grid::free();
            ok = true; why.str(""); why.clear(); step = 0;
        } else if (kind == "GRID") {
            grid = readGrid(in);
        } else if (kind == "HISTORY") {
            std::size_t limit; in >> limit;
            hist = History(limit);
        } else if (kind == "SEL") {
            std::string op; in >> op;
            if (op == "clear") { sel.clear(); continue; }
            std::string nm;
            while (in >> nm) {
                const NodeID id = md.manifold().findNode(nm);
                if (op == "only") sel.only(id);
                else if (op == "toggle") sel.toggle(id);
                else if (op == "box") sel.addFromBox(id);
            }
        } else if (kind == "DO") {
            in >> lastOp;
            ++step;
            if (lastOp == "undo") { last = hist.undo(md); continue; }
            if (lastOp == "redo") { last = hist.redo(md); continue; }

            // The operation, then History::apply -- the same call an editor
            // makes, so the rule "recorded only if it changed something" is
            // the package's own code under test, not a copy of it here.
            std::function<Result(Model&)> op;
            if (lastOp == "place") {
                float x, y; in >> x >> y;
                op = [&, x, y](Model& m) { return m.place({x, y}, grid); };
            }
            else if (lastOp == "join")    op = [&](Model& m) { return m.join(sel); };
            else if (lastOp == "unjoin")  op = [&](Model& m) { return m.unjoin(sel); };
            else if (lastOp == "remove")  op = [&](Model& m) { return m.remove(sel); };
            else if (lastOp == "newoutput") op = [&](Model& m) { return m.newOutput(); };
            else if (lastOp == "derived") op = [&](Model& m) { return m.newDerived(sel); };
            else if (lastOp == "bind")    op = [&](Model& m) { return m.bind(sel); };
            else if (lastOp == "bindall") op = [&](Model& m) { return m.bindAll(sel); };
            else if (lastOp == "fill") {
                int dir, fine; in >> dir >> fine;
                op = [&, dir, fine](Model& m) {
                    return m.stepFill(sel, dir, fine != 0); };
            }
            else if (lastOp == "clear")   op = [&](Model& m) { return m.clear(sel); };
            else if (lastOp == "cycle")   op = [&](Model& m) { return m.cycleOutput(); };
            else if (lastOp == "trim") {
                float db; in >> db;
                op = [&, db](Model& m) { return m.trimCurrent(db); };
            }
            else if (lastOp == "removeoutput") op = [&](Model& m) { return m.removeCurrentOutput(); };
            else if (lastOp == "pick") {
                std::string nm; in >> nm;
                op = [&, nm](Model& m) {
                    return m.pickOutput(m.mapping().findTarget(nm)); };
            }
            else if (lastOp == "auto")    op = [&](Model& m) { return m.toggleAutoOutput(); };
            else if (lastOp == "move") {
                std::string nm; float x, y; in >> nm >> x >> y;
                op = [&, nm, x, y](Model& m) {
                    return m.move({{m.manifold().findNode(nm), {x, y}}}); };
            }
            else if (lastOp == "example") op = [&](Model& m) {
                m.loadExample(); Result r; r.changed = true; return r; };
            else if (lastOp == "empty")   op = [&](Model& m) {
                m.newEmpty(); Result r; r.changed = true; return r; };
            else { std::cerr << "unknown op " << lastOp << "\n"; return 2; }
            last = hist.apply(md, label(lastOp), op);
        } else if (kind == "EXPECT") {
            int ch, rf; in >> ch >> rf;
            std::string rest; std::getline(in, rest);
            const std::size_t q1 = rest.find('"'), q2 = rest.rfind('"');
            const std::string msg = rest.substr(q1 + 1, q2 - q1 - 1);
            if (ok && ((last.changed ? 1 : 0) != ch
                       || (last.refused ? 1 : 0) != rf
                       || last.message != msg)) {
                ok = false;
                why << "step " << step << " (" << lastOp << "): expected "
                    << ch << " " << rf << " \"" << msg << "\", got "
                    << last.changed << " " << last.refused << " \""
                    << last.message << "\"";
            }
        } else if (kind == "STATE") {
            std::string want; std::getline(in, want);
            const std::string got = dump(md);
            if (ok && !sameState(want, got)) {
                ok = false;
                why << "step " << step << " (" << lastOp << ") state differs"
                    << "\n      want:" << want << "\n      got:  " << got;
            }
        } else if (kind == "CHART") {
            in >> chX >> chTop >> chW >> chH;
            layout = layoutChart(md.mapping(), chX, chTop, chW, chH);
        } else if (kind == "EXPECTCHART") {
            std::string first; in >> first;
            if (first == "EMPTY") {
                if (ok && !layout.empty) {
                    ok = false; why << "chart should be empty";
                }
                continue;
            }
            const float bw = std::stof(first);
            float sx, tx; in >> sx >> tx;
            bool good = !layout.empty && std::fabs(layout.barWidth - bw) < 1e-3
                     && std::fabs(layout.silenceX - sx) < 1e-3
                     && std::fabs(layout.totalX - tx) < 1e-3;
            std::string tok;
            std::size_t i = 0;
            while (good && in >> tok) {
                // ch:kind:x:name
                std::vector<std::string> f;
                std::stringstream ss(tok);
                std::string part;
                while (std::getline(ss, part, ':')) f.push_back(part);
                if (i >= layout.bars.size()) { good = false; break; }
                const ChartBar& b = layout.bars[i];
                const char* k = b.kind == ChartBar::Kind::Output ? "output"
                              : b.kind == ChartBar::Kind::Derived ? "derived"
                              : "unused";
                const std::string nm = b.name.empty() ? "-" : b.name;
                good = b.channel == std::stoi(f[0]) && f[1] == k
                    && std::fabs(b.x - std::stof(f[2])) < 1e-3 && f[3] == nm;
                ++i;
            }
            if (good && i != layout.bars.size()) good = false;
            if (ok && !good) {
                ok = false;
                why << "chart layout differs after step " << step
                    << ": bar width " << layout.barWidth << ", silence at "
                    << layout.silenceX << ", " << layout.bars.size() << " bars";
            }
        } else if (kind == "CLICK") {
            float x, y; std::string want;
            in >> x >> y >> want;
            const TargetID hit = layout.outputAt(x, y);
            const std::string got = hit == InvalidTarget
                                  ? "-" : md.mapping().targetName(hit);
            if (ok && got != want) {
                ok = false;
                why << "click at (" << x << ", " << y << ") picked " << got
                    << ", expected " << want;
            }
        } else if (kind == "ENDEDIT") {
            Tally& t = tallies[cls];
            if (ok) ++t.pass; else {
                ++t.fail;
                failures.push_back(cls + "  " + name + "\n      " + why.str());
            }
            std::cout << (ok ? "  pass  " : "  FAIL  ")
                      << std::left << std::setw(10) << cls << name << "\n";
        } else {
            std::cerr << "unknown record type: " << kind << "\n";
            return 2;
        }
    }

    int pass = 0, fail = 0;
    std::cout << "\n";
    for (const auto& kv : tallies) {
        std::cout << "  " << std::left << std::setw(10) << kv.first
                  << kv.second.pass << "/" << (kv.second.pass + kv.second.fail)
                  << "\n";
        pass += kv.second.pass; fail += kv.second.fail;
    }
    if (!failures.empty()) {
        std::cout << "\nfailures:\n";
        for (const auto& s : failures) std::cout << "  " << s << "\n";
    }
    std::cout << "\n" << pass << "/" << (pass + fail)
              << (fail == 0 ? "  GREEN\n" : "  RED\n");
    return fail == 0 ? 0 : 1;
}
