#!/usr/bin/env python3
"""
ofxManifold — independent reference for serialization.

This one has the strongest cross-check in the project. The C++ parses fixture
files with a hand-written parser in src/io; this parses the SAME files with
Python's `json` module, which is a mature independent implementation of the
format nobody involved here wrote. Agreement is real evidence.

Emits fixture files into tests/fixtures/ and the vector file that drives them.

Classes:
  ANALYTIC  known by hand: node and region counts, which malformed files must
            be refused, defaults for absent fields.
  CROSS     evaluated positions and weights, computed here.
  SPEC      our rules: duplicate keys are an error rather than last-wins,
            a dangling mapping reference is a load failure rather than a
            warning, an unknown "space" is refused rather than assumed.
"""

import json
import math
import os
import sys

TOL = 1e-6
FIXTURES = "tests/fixtures"


def fmt(x):
    """Ten significant digits. See DECISIONS.md D-006."""
    return f"{x:.10g}"


def barycentric(a, b, c, p):
    v0x, v0y = b[0] - a[0], b[1] - a[1]
    v1x, v1y = c[0] - a[0], c[1] - a[1]
    v2x, v2y = p[0] - a[0], p[1] - a[1]
    det = v0x * v1y - v1x * v0y
    if abs(det) < 1e-12:
        return None
    wB = (v2x * v1y - v1x * v2y) / det
    wC = (v0x * v2y - v2x * v0y) / det
    return (1.0 - wB - wC, wB, wC)


def biased(w, nw):
    scaled = [x * y for x, y in zip(w, nw)]
    tot = sum(scaled)
    if abs(tot) < 1e-12:
        return None
    return tuple(s / tot for s in scaled)


def contains(a, b, c, p):
    """Edge-sign test, as in reference_manifold.py."""
    def cr(o, u, v):
        return (u[0] - o[0]) * (v[1] - o[1]) - (v[0] - o[0]) * (u[1] - o[1])
    d = [cr(a, b, p), cr(b, c, p), cr(c, a, p)]
    area2 = abs(cr(a, b, c))
    eps = 1e-6 * max(area2, 1e-12)
    return not (any(x < -eps for x in d) and any(x > eps for x in d))


def evaluate(doc, p):
    """First hit in insertion order, against the parsed document."""
    names = [n["id"] for n in doc["nodes"]]
    pos = {n["id"]: tuple(n["position"]) for n in doc["nodes"]}
    wt = {n["id"]: n.get("weight", 1.0) for n in doc["nodes"]}
    for tri in doc.get("triangles", []):
        a, b, c = (pos[tri[0]], pos[tri[1]], pos[tri[2]])
        if contains(a, b, c, p):
            w = barycentric(a, b, c, p)
            if w is None:
                continue
            w = biased(w, (wt[tri[0]], wt[tri[1]], wt[tri[2]]))
            return list(zip(tri, w))
    return None


def write(name, text):
    os.makedirs(FIXTURES, exist_ok=True)
    with open(os.path.join(FIXTURES, name), "w") as f:
        f.write(text)
    return name


def build():
    out = []
    out.append("# ofxManifold serialization conformance vectors")
    out.append("# GENERATED by tests/ref/reference_serialize.py -- do not hand edit")
    out.append("#")
    out.append("# The C++ parses these fixtures with the hand-written parser in")
    out.append("# src/io; this reference parses the same files with Python's")
    out.append("# json module. That is an independent implementation of the")
    out.append("# format written by neither of us, which makes agreement here")
    out.append("# the strongest cross-check in the project.")
    out.append("")
    out.append(f"TOL {fmt(TOL)}")
    out.append("")

    # ---- good manifolds --------------------------------------------------
    simple = {
        "version": 1,
        "space": "normalized",
        "nodes": [
            {"id": "A", "position": [0.2, 0.2], "weight": 1.0},
            {"id": "B", "position": [0.8, 0.25], "weight": 1.0},
            {"id": "C", "position": [0.45, 0.85], "weight": 1.0},
        ],
        "triangles": [["A", "B", "C"]],
    }
    f = write("simple.json", json.dumps(simple, indent=2) + "\n")
    doc = json.loads(open(os.path.join(FIXTURES, f)).read())
    out.append("# a plain three-node manifold")
    out.append(f"MANIFOLD_LOAD load_simple ANALYTIC {f} OK")
    out.append(f"COUNTS counts_simple ANALYTIC {f} 3 1")
    for nm, p in (("centroid", (0.48333333, 0.43333333)),
                  ("interior", (0.45, 0.40))):
        e = evaluate(doc, p)
        out.append(f"EVAL eval_{nm} CROSS {f} {fmt(p[0])} {fmt(p[1])} "
                   + " ".join(f"{n}={fmt(w)}" for n, w in e))
    out.append(f"ROUNDTRIP roundtrip_simple ANALYTIC {f}")
    out.append("")

    # weights preserved through the file
    biased_doc = {
        "version": 1,
        "space": "normalized",
        "nodes": [
            {"id": "A", "position": [0.2, 0.2], "weight": 2.0},
            {"id": "B", "position": [0.8, 0.25], "weight": 1.0},
            {"id": "C", "position": [0.45, 0.85], "weight": 0.5},
        ],
        "triangles": [["A", "B", "C"]],
    }
    f = write("biased.json", json.dumps(biased_doc, indent=2) + "\n")
    doc = json.loads(open(os.path.join(FIXTURES, f)).read())
    e = evaluate(doc, (0.45, 0.40))
    out.append("# per-node weights must survive the file. A loader that")
    out.append("# dropped them would still produce a valid-looking manifold")
    out.append("# and every weight would be quietly wrong.")
    out.append(f"MANIFOLD_LOAD load_biased ANALYTIC {f} OK")
    out.append(f"EVAL eval_biased CROSS {f} {fmt(0.45)} {fmt(0.40)} "
               + " ".join(f"{n}={fmt(w)}" for n, w in e))
    out.append(f"ROUNDTRIP roundtrip_biased ANALYTIC {f}")
    out.append("")

    # absent weight defaults to 1
    nowt = {
        "version": 1,
        "nodes": [
            {"id": "A", "position": [0.2, 0.2]},
            {"id": "B", "position": [0.8, 0.25]},
            {"id": "C", "position": [0.45, 0.85]},
        ],
        "triangles": [["A", "B", "C"]],
    }
    f = write("no_weights.json", json.dumps(nowt, indent=2) + "\n")
    doc = json.loads(open(os.path.join(FIXTURES, f)).read())
    e = evaluate(doc, (0.45, 0.40))
    out.append("# absent weight defaults to 1, and absent \"space\" is")
    out.append("# accepted, so a hand-written file stays short")
    out.append(f"MANIFOLD_LOAD load_no_weights ANALYTIC {f} OK")
    out.append(f"EVAL eval_no_weights CROSS {f} {fmt(0.45)} {fmt(0.40)} "
               + " ".join(f"{n}={fmt(w)}" for n, w in e))
    out.append("")

    # a fan, with more topology
    fan = {
        "version": 1,
        "space": "normalized",
        "nodes": [
            {"id": "O", "position": [0.5, 0.5], "weight": 1.0},
            {"id": "N", "position": [0.5, 0.9], "weight": 1.0},
            {"id": "E", "position": [0.9, 0.5], "weight": 1.0},
            {"id": "S", "position": [0.5, 0.1], "weight": 1.0},
            {"id": "W", "position": [0.1, 0.5], "weight": 1.0},
        ],
        "triangles": [["O", "N", "E"], ["O", "E", "S"],
                      ["O", "S", "W"], ["O", "W", "N"]],
    }
    f = write("fan.json", json.dumps(fan, indent=2) + "\n")
    doc = json.loads(open(os.path.join(FIXTURES, f)).read())
    out.append("# four regions: region order must survive, since first-hit")
    out.append("# containment depends on it")
    out.append(f"MANIFOLD_LOAD load_fan ANALYTIC {f} OK")
    out.append(f"COUNTS counts_fan ANALYTIC {f} 5 4")
    for nm, p in (("q0", (0.62, 0.62)), ("q2", (0.38, 0.38))):
        e = evaluate(doc, p)
        out.append(f"EVAL eval_fan_{nm} CROSS {f} {fmt(p[0])} {fmt(p[1])} "
                   + " ".join(f"{n}={fmt(w)}" for n, w in e))
    out.append(f"ROUNDTRIP roundtrip_fan ANALYTIC {f}")
    out.append("")

    # float positions that need nine significant digits to round-trip
    # These are not round decimals. Each was chosen because it survives NINE
    # significant digits and is LOST at seven and eight -- verified by
    # round-tripping through a 32-bit float. Short decimals like 0.2 and 0.85
    # survive six, which is why an earlier version of this fixture could not
    # see the write precision drop at all.
    prec = {
        "version": 1,
        "space": "normalized",
        "nodes": [
            {"id": "A", "position": [0.103641056, 0.104602486],
             "weight": 0.110612854},
            {"id": "B", "position": [0.906023036, 0.115172684],
             "weight": 0.104594916},
            {"id": "C", "position": [0.505853565, 0.913316715],
             "weight": 0.113316715},
        ],
        "triangles": [["A", "B", "C"]],
    }
    f = write("precision.json", json.dumps(prec, indent=2) + "\n")
    out.append("# positions chosen so that six significant digits LOSE the")
    out.append("# float and nine keep it. Every other fixture here uses short")
    out.append("# decimals such as 0.2 and 0.85, which survive six digits by")
    out.append("# accident -- so the write precision was untested until this")
    out.append("# fixture existed. See DECISIONS.md D-007.")
    out.append(f"MANIFOLD_LOAD load_precision ANALYTIC {f} OK")
    out.append(f"ROUNDTRIP roundtrip_precision ANALYTIC {f}")
    out.append("")

    # strings with escapes, since node names are written back out quoted
    esc = {
        "version": 1,
        "nodes": [
            {"id": "quote\"inside", "position": [0.2, 0.2], "weight": 1.0},
            {"id": "back\\slash", "position": [0.8, 0.25], "weight": 1.0},
            {"id": "plain", "position": [0.45, 0.85], "weight": 1.0},
        ],
        "triangles": [["quote\"inside", "back\\slash", "plain"]],
    }
    f = write("escapes.json", json.dumps(esc, indent=2) + "\n")
    out.append("# escaped quotes and backslashes in node names. The writer")
    out.append("# quotes names on the way out, so a parser and a writer that")
    out.append("# disagree about escaping produce a file that will not reload.")
    out.append(f"MANIFOLD_LOAD load_escapes ANALYTIC {f} OK")
    out.append(f"COUNTS counts_escapes ANALYTIC {f} 3 1")
    out.append(f"ROUNDTRIP roundtrip_escapes ANALYTIC {f}")
    out.append("")

    # exponent notation, which a hand-rolled number parser is likely to miss
    expo = {
        "version": 1,
        "nodes": [
            {"id": "A", "position": [1e-3, 2.5e-2], "weight": 1.0},
            {"id": "B", "position": [0.8, 0.25], "weight": 1.5e0},
            {"id": "C", "position": [0.45, 8.5E-1], "weight": 1.0},
        ],
        "triangles": [["A", "B", "C"]],
    }
    txt = json.dumps(expo, indent=2).replace("0.001", "1e-3") \
                                    .replace("0.025", "2.5e-2") \
                                    .replace("1.5", "1.5e0") \
                                    .replace("0.85", "8.5E-1")
    f = write("exponents.json", txt + "\n")
    doc = json.loads(open(os.path.join(FIXTURES, f)).read())
    e = evaluate(doc, (0.45, 0.40))
    out.append("# exponent notation in several forms. A hand-rolled number")
    out.append("# parser that stopped at the decimal point would read 1e-3 as")
    out.append("# 1 and place the node in the wrong place entirely.")
    out.append(f"MANIFOLD_LOAD load_exponents ANALYTIC {f} OK")
    out.append(f"EVAL eval_exponents CROSS {f} {fmt(0.45)} {fmt(0.40)} "
               + " ".join(f"{n}={fmt(w)}" for n, w in e))
    out.append("")

    # ---- files that must be refused --------------------------------------
    bad = [
        ("bad_trailing_comma.json",
         '{ "version": 1, "nodes": [], }',
         "ANALYTIC", "trailing comma is not JSON", "expected"),
        ("bad_unterminated.json",
         '{ "version": 1, "nodes": [',
         "ANALYTIC", "truncated file", "unexpected_end"),
        ("bad_no_version.json",
         '{ "nodes": [] }',
         "ANALYTIC", "a file with no version cannot be interpreted safely", "missing_version"),
        ("bad_future_version.json",
         '{ "version": 99, "nodes": [] }',
         "ANALYTIC",
         "a future version is refused rather than read as best it can be", "unsupported_version"),
        ("bad_unknown_space.json",
         '{ "version": 1, "space": "pixels", "nodes": [] }',
         "SPEC",
         "an unknown space is refused rather than assumed normalized -- "
         "reading pixel coordinates as normalized would put every node "
         "within a fraction of the origin and look like a collapsed map", "unsupported_space"),
        ("bad_duplicate_key.json",
         '{ "version": 1, "nodes": [], "triangles": [], "triangles": [] }',
         "SPEC",
         "duplicate keys are an error, not last-wins. Note the duplicate is "
         "\"triangles\" and both values are VALID -- a last-wins parser would "
         "load this file happily. An earlier version of this fixture "
         "duplicated \"version\" with values 1 and 2, which a last-wins "
         "parser also rejected, as an unsupported version. It passed on a "
         "coincidence and tested nothing (D-007)", "duplicate_key"),
        ("bad_duplicate_node.json",
         '{ "version": 1, "nodes": ['
         '{"id":"A","position":[0.1,0.1]},'
         '{"id":"A","position":[0.9,0.9]}] }',
         "ANALYTIC", "two nodes with the same id", "duplicate_node_id"),
        ("bad_dangling_triangle.json",
         '{ "version": 1, "nodes": [{"id":"A","position":[0.1,0.1]}],'
         ' "triangles": [["A","B","C"]] }',
         "ANALYTIC", "a triangle naming a node that does not exist", "unknown_node"),
        ("bad_degenerate_triangle.json",
         '{ "version": 1, "nodes": ['
         '{"id":"A","position":[0.1,0.1]},'
         '{"id":"B","position":[0.4,0.4]},'
         '{"id":"C","position":[0.7,0.7]}],'
         ' "triangles": [["A","B","C"]] }',
         "ANALYTIC",
         "collinear vertices: refused at load, not discovered at evaluate", "degenerate"),
        ("bad_short_position.json",
         '{ "version": 1, "nodes": [{"id":"A","position":[0.1]}] }',
         "ANALYTIC", "a position with one component", "position"),
        ("bad_trailing_junk.json",
         '{ "version": 1, "nodes": [] } garbage',
         "ANALYTIC", "content after the closing brace", "trailing_content"),
        ("bad_root_array.json",
         '[1, 2, 3]',
         "ANALYTIC", "the root is not an object", "not_an_object"),
        ("bad_unterminated_string.json",
         '"abc',
         "ANALYTIC",
         "an unterminated string as the ROOT value. This is the only place "
         "the fault is observable: anywhere inside an object or array, the "
         "enclosing container fails first and hides it. With no container, a "
         "parser that returned the partial string would report 'root is not "
         "an object' instead, which is the wrong diagnosis for the file",
         "unterminated"),
    ]
    out.append("# files that must be REFUSED. A loader that accepts these")
    out.append("# hands back a manifold that is wrong rather than absent,")
    out.append("# which is worse than failing.")
    out.append("#")
    out.append("# Each rejection also asserts a SUBSTRING of the error. That is")
    out.append("# not decoration: a loader can refuse a file for the right")
    out.append("# verdict and the wrong reason, and the person reading the")
    out.append("# message at six in the evening is the one who pays. Checking")
    out.append("# only accept/reject let a mutation through that dropped the")
    out.append("# dangling-node check entirely -- the file was still refused,")
    out.append("# by a later guard, with a message naming the wrong problem.")
    out.append("# Substrings are OUR message text, hence SPEC where they are")
    out.append("# the only thing under test.")
    for name, text, cls, note, err in bad:
        write(name, text + "\n")
        out.append(f"# {note}")
        out.append(f"MANIFOLD_LOAD reject_{name[4:-5]} {cls} {name} FAIL "
                   f"{err}")
    out.append("")

    # ---- mapping ---------------------------------------------------------
    mapping = {
        "version": 1,
        "bindings": [
            {"node": "A", "target": "out.1", "weight": 1.0},
            {"node": "B", "target": "out.2", "weight": 1.0},
            {"node": "C", "target": "corner.NW", "weight": 3.0},
            {"node": "C", "target": "corner.NE", "weight": 1.0},
        ],
        "aggregators": [
            {"name": "sub.house", "mode": "linear", "sources": ["A", "B"]},
            {"name": "sub.power", "mode": "power", "sources": ["A", "B"]},
        ],
    }
    f = write("mapping_simple.json", json.dumps(mapping, indent=2) + "\n")
    out.append("# a mapping loaded against simple.json. Bindings refer to")
    out.append("# nodes BY NAME: NodeIDs are runtime handles whose values")
    out.append("# depend on insertion order, and writing them to disk would")
    out.append("# make the file silently wrong the moment someone reorders")
    out.append("# the nodes in their manifold.")
    out.append(f"MAPPING_LOAD load_mapping ANALYTIC simple.json {f} OK")
    out.append(f"MAPPING_TARGETS mapping_targets ANALYTIC simple.json {f} 4")
    out.append("# Target NAMES, not just how many. Counting alone cannot see a")
    out.append("# writer that emits numeric ids instead of names: the file")
    out.append("# reloads into four targets called \"0\" through \"3\", the count")
    out.append("# matches, byte stability holds, and every OSC address in the")
    out.append("# show is wrong.")
    out.append(f"MAPPING_NAMES mapping_names ANALYTIC simple.json {f} "
               "out.1 out.2 corner.NW corner.NE")
    out.append(f"MAPPING_ROUNDTRIP roundtrip_mapping ANALYTIC simple.json {f}")
    out.append("")

    bad_map = [
        ("bad_map_dangling.json",
         '{ "version": 1, "bindings": [{"node":"Z","target":"out.1"}] }',
         "SPEC",
         "a binding naming a node the manifold does not have. A mapping is "
         "only meaningful against a manifold, so this is a load failure "
         "rather than a warning", "unknown_node"),
        ("bad_map_mode.json",
         '{ "version": 1, "aggregators": ['
         '{"name":"x","mode":"quadratic","sources":["A"]}] }',
         "ANALYTIC", "an aggregator mode that does not exist", "unknown_aggregator_mode"),
        ("bad_map_no_version.json",
         '{ "bindings": [] }',
         "ANALYTIC", "no version", "version"),
    ]
    for name, text, cls, note, err in bad_map:
        write(name, text + "\n")
        out.append(f"# {note}")
        out.append(f"MAPPING_LOAD reject_{name[8:-5]} {cls} simple.json "
                   f"{name} FAIL {err}")

    return out


def main():
    out = build()
    path = "tests/vectors/serialize.vec"
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    counts = {}
    for line in out:
        p = line.split()
        if p and p[0] in ("MANIFOLD_LOAD", "COUNTS", "EVAL", "ROUNDTRIP",
                          "MAPPING_LOAD", "MAPPING_TARGETS",
                          "MAPPING_ROUNDTRIP"):
            counts[p[2]] = counts.get(p[2], 0) + 1
    print(f"wrote {path}")
    print(f"wrote fixtures into {FIXTURES}/")
    for k in ("ANALYTIC", "CROSS", "SPEC"):
        print(f"  {k:9s} {counts.get(k, 0)}")
    print(f"  {'TOTAL':9s} {sum(counts.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
