#!/usr/bin/env python3
"""
ofxManifold — independent reference for weight smoothing.

A DIFFERENT TESTING SHAPE from everything else in this project.

Every other suite tests a pure function: one input, one expected output, order
irrelevant. A smoother has memory, so a single call means nothing. Its vectors
are SEQUENCES -- snap to a state, then tick, and tick, and tick, asserting the
output at each step. A smoother that was right on the first tick and wrong on
the fourth would pass any single-shot check.

Formulation differs from the C++ where it can: the C++ walks its state vector
and then scans the target for each id; this builds dicts of both and works over
the union. Different traversal, same arithmetic.

Classes:
  ANALYTIC  known by hand -- passthrough when disabled, exactly half the
            distance after exactly one half-life, partition of unity through a
            disjoint transition, the slew bound, snap, and dt <= 0.
  CROSS     step-by-step values from this reference.
  SPEC      our rules: pruning threshold, the decision not to renormalize, the
            order in which exponential and slew are applied.
"""

import sys

TOL = 1e-6
PRUNE = 1e-4


def fmt(x):
    """Ten significant digits. See DECISIONS.md D-006."""
    return f"{x:.10g}"


def wv(v):
    return " ".join(f"{i}={fmt(w)}" for i, w in v)


class Smoother:
    def __init__(self, half_life, max_rate):
        self.half_life = half_life
        self.max_rate = max_rate
        self.state = []          # list of (id, weight), insertion ordered

    def snap(self, v):
        self.state = list(v)

    def _step(self, frm, to, alpha, max_step):
        v = frm + (to - frm) * alpha
        if max_step > 0.0:
            d = v - frm
            if d > max_step:
                v = frm + max_step
            if d < -max_step:
                v = frm - max_step
        return v

    def update(self, target, dt):
        if self.half_life <= 0.0 and self.max_rate <= 0.0:
            self.state = list(target)
            return self.state
        if dt <= 0.0:
            return self.state

        alpha = (1.0 - 0.5 ** (dt / self.half_life)) \
            if self.half_life > 0.0 else 1.0
        max_step = self.max_rate * dt if self.max_rate > 0.0 else 0.0

        tgt = {i: w for i, w in target}
        nxt = []

        # Existing entries first, preserving order, moving toward their target
        # -- which is zero for a node the target no longer names.
        for i, w in self.state:
            nxt.append((i, self._step(w, tgt.get(i, 0.0), alpha, max_step)))

        # Then nodes the target has and the state does not, entering from zero.
        known = {i for i, _ in self.state}
        for i, w in target:
            if i not in known:
                nxt.append((i, self._step(0.0, w, alpha, max_step)))

        # Prune only what has decayed AND is unwanted. A node genuinely held at
        # a tiny weight must stay, or it would flicker.
        self.state = [(i, w) for i, w in nxt
                      if abs(w) >= PRUNE or i in tgt]
        return self.state

    def settled(self, target, eps=1e-3):
        tgt = {i: w for i, w in target}
        cur = {i: w for i, w in self.state}
        for i, w in tgt.items():
            if abs(cur.get(i, 0.0) - w) > eps:
                return False
        for i, w in cur.items():
            if i not in tgt and abs(w) > eps:
                return False
        return True


def block(out, name, cls, half_life, max_rate, dt, snap, ticks, note=""):
    """Emit one sequence: snap, then a run of ticks with expected output."""
    if note:
        out.append(f"# {note}")
    out.append(f"SMOOTH {name} {cls} HALFLIFE {fmt(half_life)} "
               f"MAXRATE {fmt(max_rate)} DT {fmt(dt)}")
    sm = Smoother(half_life, max_rate)
    if snap is not None:
        sm.snap(snap)
        out.append("SNAP " + wv(snap))
    for target in ticks:
        st = sm.update(target, dt)
        out.append("TICK " + wv(target) + " EXPECT " + wv(st))
    out.append("ENDSMOOTH")
    out.append("")
    return sm


def build():
    out = []
    out.append("# ofxManifold smoother conformance vectors")
    out.append("# GENERATED by tests/ref/reference_smoother.py -- do not hand edit")
    out.append("#")
    out.append("# SEQUENCES, not single calls. A smoother has memory, so one")
    out.append("# call proves nothing: an implementation right on the first")
    out.append("# tick and wrong on the fourth passes any single-shot check.")
    out.append("")
    out.append(f"TOL {fmt(TOL)}")
    out.append("")

    a = [(0, 0.5), (1, 0.3), (2, 0.2)]
    b = [(5, 0.6), (6, 0.4)]
    dt60 = 1.0 / 60.0

    # ---- disabled is exact passthrough ----------------------------------
    block(out, "disabled_passthrough", "ANALYTIC", 0.0, 0.0, dt60,
          a, [b, b, a],
          "half-life 0 and no slew limit: the target passes through "
          "untouched, immediately, every tick. Smoothing must be something "
          "you can turn off completely")

    out.append("# Disabled AND dt = 0. The early return for a disabled")
    out.append("# smoother sits BEFORE the dt check, deliberately: if")
    out.append("# smoothing is off, elapsed time is irrelevant and the target")
    out.append("# should pass through regardless.")
    out.append("#")
    out.append("# This is the only case that distinguishes the early return")
    out.append("# from the general path. With half-life 0 the general path")
    out.append("# computes alpha = 1 and lands on the target anyway, so every")
    out.append("# other disabled vector passes either way -- the early return")
    out.append("# looked like an untested optimization until dt = 0 was tried.")
    block(out, "disabled_zero_dt", "ANALYTIC", 0.0, 0.0, 0.0,
          a, [b, b],
          "")

    # ---- exactly one half-life ------------------------------------------
    #
    # dt == halfLife, so each tick closes exactly half the remaining distance.
    # Hand-checkable: 0 -> 0.5 -> 0.75 -> 0.875 of the way there.
    block(out, "one_half_life_per_tick", "ANALYTIC", 0.25, 0.0, 0.25,
          [(0, 0.0)], [[(0, 1.0)]] * 4,
          "dt equals the half-life exactly, so each tick closes half the "
          "remaining distance: 0.5, 0.75, 0.875, 0.9375. This is what "
          "'half-life' has to mean, checked rather than assumed")

    # ---- frame-rate independence ----------------------------------------
    #
    # The same elapsed time at two rates must reach the same place. This is
    # the reason the API takes a half-life and a dt rather than a per-frame
    # coefficient.
    s1 = Smoother(0.1, 0.0)
    s1.snap([(0, 0.0)])
    for _ in range(6):
        s1.update([(0, 1.0)], 1.0 / 60.0)
    s2 = Smoother(0.1, 0.0)
    s2.snap([(0, 0.0)])
    for _ in range(3):
        s2.update([(0, 1.0)], 1.0 / 30.0)
    out.append("# FRAME-RATE INDEPENDENCE. Six ticks at 60fps and three at")
    out.append("# 30fps cover the same 0.1 seconds and must land in the same")
    out.append("# place. A per-frame coefficient would not: a smoother tuned")
    out.append("# in rehearsal on one machine would behave differently on")
    out.append("# another, which is a bad surprise on an opening night.")
    out.append(f"RATEMATCH rate_independent ANALYTIC 0.1 "
               f"{fmt(1.0/60.0)} 6 {fmt(1.0/30.0)} 3 "
               f"TARGET 0=1 EXPECT {fmt(s1.state[0][1])}")
    out.append("")

    # ---- partition of unity through a disjoint transition ---------------
    out.append("# PARTITION OF UNITY, through a transition between two")
    out.append("# weight vectors that share NO nodes at all.")
    out.append("#")
    out.append("# Exponential smoothing preserves it exactly. The smoothed")
    out.append("# vector is a lerp between two vectors that each sum to one,")
    out.append("# taken over their union with absent nodes at zero, so the")
    out.append("# sum is a lerp of 1 and 1.")
    out.append("#")
    out.append("# This is worth knowing rather than assuming, because it")
    out.append("# means smoothing can sit anywhere in the chain without")
    out.append("# disturbing the invariant every other layer relies on.")
    sm = Smoother(0.1, 0.0)
    sm.snap(a)
    for k in range(1, 13):
        st = sm.update(b, dt60)
        total = sum(w for _, w in st)
        if k in (1, 2, 4, 8, 12):
            out.append(f"SUMAT sum_disjoint_{k} ANALYTIC 0.1 0 {fmt(dt60)} "
                       f"SNAP " + wv(a) + " TARGET " + wv(b) +
                       f" TICKS {k} SUM {fmt(total)}")
    out.append("")

    # ---- the slew limit does NOT preserve it ----------------------------
    out.append("# A SLEW LIMIT DOES NOT preserve partition of unity during a")
    out.append("# transition, and that is not a bug to be corrected.")
    out.append("#")
    out.append("# Each component is clamped independently, so while three")
    out.append("# nodes fall and two rise the totals do not balance. The sum")
    out.append("# dips, holds while the rates happen to match, and recovers")
    out.append("# to one once the departing nodes reach zero.")
    out.append("#")
    out.append("# Renormalizing would hide it and would break the bound the")
    out.append("# caller asked for -- the whole point of a slew limit is that")
    out.append("# nothing moves faster than the stated rate. Recorded rather")
    out.append("# than fixed.")
    sm = Smoother(0.0, 2.0)
    sm.snap(a)
    for k in range(1, 41):
        st = sm.update(b, dt60)
        total = sum(w for _, w in st)
        if k in (1, 5, 10, 20, 40):
            cls = "SPEC" if k < 20 else "ANALYTIC"
            out.append(f"SUMAT sum_slewed_{k} {cls} 0 2 {fmt(dt60)} "
                       f"SNAP " + wv(a) + " TARGET " + wv(b) +
                       f" TICKS {k} SUM {fmt(total)}")
    out.append("")

    # ---- the slew bound itself ------------------------------------------
    out.append("# The bound itself: no component may move by more than")
    out.append("# maxRate * dt in one tick, however far away its target is.")
    block(out, "slew_bounded", "ANALYTIC", 0.0, 2.0, dt60,
          [(0, 0.0)], [[(0, 1.0)]] * 5,
          "target 1.0 from 0.0 with a 2.0/s limit at 1/60s: exactly "
          "0.0333 per tick, five ticks reaching 0.1667")

    # ---- ordinary sequences ---------------------------------------------
    block(out, "converge_same_set", "CROSS", 0.08, 0.0, dt60,
          a, [[(0, 0.2), (1, 0.2), (2, 0.6)]] * 6,
          "same node set, weights moving")

    block(out, "disjoint_transition", "CROSS", 0.08, 0.0, dt60,
          a, [b] * 6, "the node set changes completely")

    block(out, "partial_overlap", "CROSS", 0.08, 0.0, dt60,
          a, [[(1, 0.4), (2, 0.3), (7, 0.3)]] * 5,
          "one node leaves, one arrives, two persist -- the ordinary case "
          "when a point crosses a region boundary")

    block(out, "hull_exit", "CROSS", 0.08, 0.0, dt60,
          a, [[]] * 6,
          "the point leaves the hull and the target becomes EMPTY. Every "
          "node decays toward zero rather than vanishing in one frame, "
          "which is the fade a hull exit should sound like")

    block(out, "both_enabled", "CROSS", 0.05, 3.0, dt60,
          a, [b] * 6,
          "exponential and slew together: the exponential result is "
          "computed first and then clamped by the rate")

    # ---- pruning ---------------------------------------------------------
    out.append("# PRUNING. A node that has decayed below the threshold AND is")
    out.append("# no longer wanted is dropped, or a source that wandered the")
    out.append("# whole map would carry an entry for every node it ever")
    out.append("# touched.")
    sm = Smoother(0.02, 0.0)
    sm.snap([(0, 1.0)])
    counts = []
    for k in range(1, 21):
        st = sm.update([(1, 1.0)], dt60)
        counts.append(len(st))
    out.append(f"PRUNE prune_drops_decayed ANALYTIC 0.02 0 {fmt(dt60)} "
               f"SNAP 0=1 TARGET 1=1 TICKS 20 "
               f"FINALCOUNT {counts[-1]}")
    out.append("")
    out.append("# but a node genuinely HELD at a tiny weight must not be")
    out.append("# pruned, or it would flicker out and back as the point moved")
    tiny = [(0, 0.5), (1, 0.5), (2, 1e-5)]
    sm = Smoother(0.02, 0.0)
    sm.snap(tiny)
    for _ in range(30):
        st = sm.update(tiny, dt60)
    out.append(f"PRUNE prune_keeps_held SPEC 0.02 0 {fmt(dt60)} "
               f"SNAP " + wv(tiny) + " TARGET " + wv(tiny) +
               f" TICKS 30 FINALCOUNT {len(st)}")
    out.append("")

    # ---- degenerate steps ------------------------------------------------
    out.append("# dt of zero or less leaves the state untouched rather than")
    out.append("# dividing by it")
    block(out, "zero_dt", "ANALYTIC", 0.1, 0.0, 0.0,
          a, [b, b], "")

    # ---- settled ---------------------------------------------------------
    out.append("# settled() answers when a transition is over. Exponential")
    out.append("# smoothing never exactly arrives, so a consumer needs a")
    out.append("# threshold, and picking it once is better than every caller")
    out.append("# picking a different one.")
    sm = Smoother(0.05, 0.0)
    sm.snap(a)
    first = None
    for k in range(1, 60):
        sm.update(b, dt60)
        if sm.settled(b) and first is None:
            first = k
    out.append(f"SETTLED settles_eventually ANALYTIC 0.05 0 {fmt(dt60)} "
               f"SNAP " + wv(a) + " TARGET " + wv(b) +
               f" FIRSTSETTLED {first}")
    return out


def main():
    out = build()
    path = "tests/vectors/smoother.vec"
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    counts = {}
    for line in out:
        p = line.split()
        if p and p[0] in ("SMOOTH", "RATEMATCH", "SUMAT", "PRUNE", "SETTLED"):
            counts[p[2]] = counts.get(p[2], 0) + 1
    print(f"wrote {path}")
    for k in ("ANALYTIC", "CROSS", "SPEC"):
        print(f"  {k:9s} {counts.get(k, 0)}")
    print(f"  {'TOTAL':9s} {sum(counts.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
