#!/usr/bin/env python3
"""
ofxManifold — independent reference for the interpretation layer.

Formulations are deliberately different from the C++ wherever a difference is
possible:

  cosine curve   C++ uses sin(w * pi/2); this uses cos((1-w) * pi/2).
                 Algebraically identical, different call.
  blend merge    C++ merges with a linear scan over the output vector; this
                 merges with a dict keyed by node id.
  spread         C++ seeds a uniform floor and adds the localized part on top;
                 this computes each component as an explicit lerp.

Where no meaningful difference exists -- sqrt is sqrt -- the vectors are classed
ANALYTIC and their expected values are stated by hand rather than computed, so
the check does not depend on this file being right.

Classes:
  ANALYTIC  known by hand. Endpoint identities, exact values at 0.25/0.5/1.0,
            constant-power sums, spread limits, blend endpoints.
  CROSS     from this reference.
  SPEC      follows a rule we invented: that curves do not renormalize, that
            spread is linear in weight space, that zero-weight entries are
            dropped from a blend.
"""

import math
import sys

TOL = 1e-6
HALF_PI = math.pi / 2.0


def c_linear(w):
    return w


def c_equal_power(w):
    return 0.0 if w <= 0.0 else math.sqrt(w)


def c_cosine(w):
    # C++ computes sin(w * pi/2). This computes cos((1-w) * pi/2).
    if w <= 0.0:
        return 0.0
    if w >= 1.0:
        return 1.0
    return math.cos((1.0 - w) * HALF_PI)


CURVES = {"linear": c_linear, "equalPower": c_equal_power, "cosine": c_cosine}


def apply_curve(v, name):
    fn = CURVES[name]
    return [(i, fn(w)) for i, w in v]


def normalize(v):
    s = sum(w for _, w in v)
    if abs(s) < 1e-9:
        return list(v)
    return [(i, w / s) for i, w in v]


def spread(v, amount, total):
    """Explicit per-component lerp toward uniform, rather than a seeded floor."""
    if amount <= 0.0 or total == 0:
        return list(v)
    amount = min(amount, 1.0)
    uniform = 1.0 / total
    src = {i: w for i, w in v}
    return [(i, (1.0 - amount) * src.get(i, 0.0) + amount * uniform)
            for i in range(total)]


def blend(a, b, t, curve_name="linear"):
    """Dict-based merge, rather than the C++'s linear scan."""
    t = max(0.0, min(1.0, t))
    fn = CURVES[curve_name]
    ga, gb = fn(1.0 - t), fn(t)

    acc = {}
    order = []
    for i, w in a:
        if i not in acc:
            acc[i] = 0.0
            order.append(i)
        acc[i] += w * ga
    for i, w in b:
        if i not in acc:
            acc[i] = 0.0
            order.append(i)
        acc[i] += w * gb
    return [(i, acc[i]) for i in order if abs(acc[i]) >= 1e-9]


def fmt(x):
    return f"{x:.17g}"


def wv(v):
    return " ".join(f"{i}={fmt(w)}" for i, w in v)


def build():
    out = []
    out.append("# ofxManifold interpretation layer conformance vectors")
    out.append("# GENERATED by tests/ref/reference_interpretation.py -- do not hand edit")
    out.append("#")
    out.append("# The C++ and this reference use different formulations where a")
    out.append("# difference is possible: cosine via sin(w*pi/2) vs cos((1-w)*pi/2),")
    out.append("# blend merge by linear scan vs by dict, spread as seeded floor vs")
    out.append("# explicit lerp. Where sqrt is simply sqrt, the vectors are ANALYTIC")
    out.append("# and state their expected values by hand.")
    out.append("")
    out.append(f"TOL {fmt(TOL)}")
    out.append("")

    # Two- and three-node inputs, both summing to one.
    two = [(0, 0.5), (1, 0.5)]
    three = [(0, 0.2), (1, 0.5), (2, 0.3)]
    quarter = [(0, 0.25), (1, 0.75)]

    # ---- curves: hand-known values --------------------------------------
    out.append("# linear is the identity. Anything else means apply() is not")
    out.append("# leaving the weights alone.")
    out.append(f"CURVE linear_is_identity ANALYTIC linear IN {wv(three)} "
               f"OUT {wv(three)}")
    out.append("")

    out.append("# sqrt(0.25) is exactly 0.5 and sqrt(0.75) is not -- an")
    out.append("# asymmetric input so a swapped pair cannot pass")
    out.append(f"CURVE equalpower_quarter ANALYTIC equalPower IN {wv(quarter)} "
               f"OUT 0={fmt(0.5)} 1={fmt(math.sqrt(0.75))}")
    out.append("")

    out.append("# both endpoints are fixed points of every curve: fn(0)==0 and")
    out.append("# fn(1)==1. blend relies on this for its endpoint identities.")
    for nm in ("linear", "equalPower", "cosine"):
        out.append(f"CURVE endpoints_{nm} ANALYTIC {nm} IN 0=0 1=1 "
                   f"OUT 0=0 1=1")
    out.append("")

    out.append(f"CURVE cosine_half ANALYTIC cosine IN {wv(two)} "
               f"OUT 0={fmt(math.sin(0.25 * math.pi))} "
               f"1={fmt(math.sin(0.25 * math.pi))}")
    out.append("")

    out.append("# Non-contiguous, non-zero-based node IDs. Every other vector")
    out.append("# here uses 0,1,2, which an implementation that REINDEXES its")
    out.append("# output would satisfy by accident. Identity is the thing the")
    out.append("# whole architecture is built to retain, so it gets a case")
    out.append("# where losing it is visible.")
    sparse = [(5, 0.25), (2, 0.5), (9, 0.25)]
    out.append(f"CURVE identity_sparse_ids ANALYTIC linear IN {wv(sparse)} "
               f"OUT {wv(sparse)}")
    out.append(f"CURVE equalpower_sparse_ids CROSS equalPower IN {wv(sparse)} "
               f"OUT {wv(apply_curve(sparse, 'equalPower'))}")
    out.append("")

    out.append(f"CURVE equalpower_three CROSS equalPower IN {wv(three)} "
               f"OUT {wv(apply_curve(three, 'equalPower'))}")
    out.append(f"CURVE cosine_three CROSS cosine IN {wv(three)} "
               f"OUT {wv(apply_curve(three, 'cosine'))}")
    out.append("")

    # ---- the property the curves exist for -------------------------------
    out.append("# Constant power. For a TWO-node vector summing to one, both")
    out.append("# equalPower and cosine produce gains whose squares sum to one.")
    out.append("# This is the whole reason equal-power exists, so it is asserted")
    out.append("# directly rather than inferred from the values above.")
    out.append(f"POWER power_equalpower_two ANALYTIC equalPower IN {wv(two)} "
               f"SUMSQ 1.0")
    out.append(f"POWER power_cosine_two ANALYTIC cosine IN {wv(two)} SUMSQ 1.0")
    out.append(f"POWER power_equalpower_asym ANALYTIC equalPower "
               f"IN {wv(quarter)} SUMSQ 1.0")
    out.append("")
    out.append("# For THREE nodes the two curves diverge -- equalPower still")
    out.append("# sums its squares to one, cosine does not. They are different")
    out.append("# instruments, not two spellings of one.")
    out.append(f"POWER power_equalpower_three ANALYTIC equalPower "
               f"IN {wv(three)} SUMSQ 1.0")
    p3 = sum(w * w for _, w in apply_curve(three, "cosine"))
    out.append(f"POWER power_cosine_three CROSS cosine IN {wv(three)} "
               f"SUMSQ {fmt(p3)}")
    out.append("")

    out.append("# A curve must NOT renormalize. equalPower on a vector summing")
    out.append("# to one gives a sum well above one, and that is correct: it")
    out.append("# preserves power instead. Renormalizing here would undo the")
    out.append("# only thing the curve was for.")
    ep2 = apply_curve(two, "equalPower")
    out.append(f"SUM sum_after_equalpower SPEC equalPower IN {wv(two)} "
               f"SUM {fmt(sum(w for _, w in ep2))}")
    out.append("")

    out.append("# normalize() restores partition of unity when a caller")
    out.append("# explicitly asks, discarding the power property to do it")
    out.append(f"NORMALIZE normalize_after_curve SPEC equalPower IN {wv(two)} "
               f"OUT {wv(normalize(ep2))}")
    out.append("")

    # ---- spread ----------------------------------------------------------
    out.append("# spread 0 is the identity, and preserves sparsity: the common")
    out.append("# case must cost nothing")
    out.append(f"SPREAD spread_zero ANALYTIC 0.0 5 IN {wv(three)} "
               f"OUT {wv(three)}")
    out.append("")
    out.append("# spread 1 is uniform over every node in the map, regardless of")
    out.append("# what the point was doing")
    out.append(f"SPREAD spread_full ANALYTIC 1.0 5 IN {wv(three)} "
               f"OUT {wv([(i, 0.2) for i in range(5)])}")
    out.append("")
    out.append("# halfway: the localized part halved, plus a uniform floor")
    out.append(f"SPREAD spread_half CROSS 0.5 5 IN {wv(three)} "
               f"OUT {wv(spread(three, 0.5, 5))}")
    out.append(f"SPREAD spread_quarter CROSS 0.25 4 IN {wv(two)} "
               f"OUT {wv(spread(two, 0.25, 4))}")
    out.append("")
    out.append("# spread must preserve partition of unity at every amount --")
    out.append("# it is a linear interpolation between two vectors that each")
    out.append("# sum to one, so the result does too")
    for amt in (0.1, 0.33, 0.5, 0.9):
        out.append(f"SPREADSUM spreadsum_{str(amt).replace('.', '_')} ANALYTIC "
                   f"{fmt(amt)} 5 IN {wv(three)} SUM 1.0")
    out.append("")
    out.append("# sparse IDs through spread: the localized part must land on")
    out.append("# the nodes it names, not on the first few slots")
    sparse_s = [(7, 0.6), (3, 0.4)]
    out.append(f"SPREAD spread_sparse_ids CROSS 0.4 12 IN {wv(sparse_s)} "
               f"OUT {wv(spread(sparse_s, 0.4, 12))}")
    out.append("")
    out.append("# amounts outside [0,1] clamp rather than extrapolating into")
    out.append("# negative weights")
    out.append(f"SPREAD spread_clamps_high SPEC 1.5 5 IN {wv(three)} "
               f"OUT {wv([(i, 0.2) for i in range(5)])}")
    out.append(f"SPREAD spread_clamps_low SPEC -0.5 5 IN {wv(three)} "
               f"OUT {wv(three)}")
    out.append("")

    # ---- blend -----------------------------------------------------------
    a = [(0, 0.6), (1, 0.4)]
    b = [(2, 0.3), (3, 0.7)]
    overlap = [(1, 0.5), (2, 0.5)]

    out.append("# blend endpoints are identities for every curve, because every")
    out.append("# curve fixes 0 and 1")
    for nm in ("linear", "equalPower", "cosine"):
        out.append(f"BLEND blend_t0_{nm} ANALYTIC 0.0 {nm} "
                   f"A {wv(a)} B {wv(b)} OUT {wv(a)}")
        out.append(f"BLEND blend_t1_{nm} ANALYTIC 1.0 {nm} "
                   f"A {wv(a)} B {wv(b)} OUT {wv(b)}")
    out.append("")

    out.append("# disjoint node sets, which is the normal case when the two")
    out.append("# vectors come from two different manifolds")
    out.append(f"BLEND blend_disjoint_half CROSS 0.5 linear "
               f"A {wv(a)} B {wv(b)} OUT {wv(blend(a, b, 0.5))}")
    out.append("")
    out.append("# overlapping node sets: shared nodes accumulate rather than")
    out.append("# one input winning")
    out.append(f"BLEND blend_overlap CROSS 0.5 linear "
               f"A {wv(a)} B {wv(overlap)} OUT {wv(blend(a, overlap, 0.5))}")
    out.append("")
    out.append("# blending a vector with itself must return it unchanged at any")
    out.append("# t under the linear curve -- a merge that dropped or doubled")
    out.append("# shared nodes fails here and nowhere else")
    for t in (0.25, 0.5, 0.75):
        out.append(f"BLEND blend_self_{str(t).replace('.', '_')} ANALYTIC "
                   f"{fmt(t)} linear A {wv(three)} B {wv(three)} "
                   f"OUT {wv(three)}")
    out.append("")
    out.append("# constant-power crossfade: with equalPower the two gains'")
    out.append("# squares sum to one, so a source moving between two maps holds")
    out.append("# its power through the transition")
    out.append(f"BLEND blend_equalpower_half CROSS 0.5 equalPower "
               f"A {wv(a)} B {wv(b)} OUT {wv(blend(a, b, 0.5, 'equalPower'))}")
    out.append(f"BLEND blend_cosine_third CROSS 0.3333333333333333 cosine "
               f"A {wv(a)} B {wv(b)} "
               f"OUT {wv(blend(a, b, 1/3, 'cosine'))}")
    out.append("")
    out.append("# a linear blend of two vectors that each sum to one also sums")
    out.append("# to one; an equal-power blend does NOT, and must not be")
    out.append("# corrected into doing so")
    out.append(f"BLENDSUM blendsum_linear ANALYTIC 0.5 linear "
               f"A {wv(a)} B {wv(b)} SUM 1.0")
    bs = sum(w for _, w in blend(a, b, 0.5, "equalPower"))
    out.append(f"BLENDSUM blendsum_equalpower SPEC 0.5 equalPower "
               f"A {wv(a)} B {wv(b)} SUM {fmt(bs)}")
    out.append("")
    out.append("# sparse IDs through blend, including one node shared between")
    out.append("# the two inputs at a non-zero index")
    sa = [(4, 0.6), (8, 0.4)]
    sb = [(8, 0.5), (1, 0.5)]
    out.append(f"BLEND blend_sparse_ids CROSS 0.5 linear "
               f"A {wv(sa)} B {wv(sb)} OUT {wv(blend(sa, sb, 0.5))}")
    out.append("")
    out.append("# t outside [0,1] clamps")
    out.append(f"BLEND blend_clamps_high SPEC 2.0 linear "
               f"A {wv(a)} B {wv(b)} OUT {wv(b)}")
    out.append(f"BLEND blend_clamps_low SPEC -1.0 linear "
               f"A {wv(a)} B {wv(b)} OUT {wv(a)}")
    return out


def main():
    out = build()
    path = "tests/vectors/interpretation.vec"
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")

    counts = {}
    for line in out:
        p = line.split()
        if p and p[0] in ("CURVE", "POWER", "SUM", "NORMALIZE", "SPREAD",
                          "SPREADSUM", "BLEND", "BLENDSUM"):
            counts[p[2]] = counts.get(p[2], 0) + 1
    print(f"wrote {path}")
    for k in ("ANALYTIC", "CROSS", "SPEC"):
        print(f"  {k:9s} {counts.get(k, 0)}")
    print(f"  {'TOTAL':9s} {sum(counts.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
